### PR TITLE
WebAPI refactor && JVM thread stats

### LINKED ISSUE #5328: API Webserver Shutdown does not free port
Running tests with `bin/rspec  ./logstash-core/spec --seed 49545` exposes a flaw. The `stop_webserver` call does not actually free the port. This makes tests with this seed fail.

### PR DESCRIPTION
**Pull request by andrewvc**
WIP for adding the stats mentioned in #4923 

Fixes #5328 

Refactors: 

1. All classes renamed to be consistent with their location on the FS path.
1. Rack app changed to no longer use init.ru, but use direct class instantiation (as a result we don't need a nested 'lib' folder under logstash/api.
1. Commands refactored to handle multiple responsibilities with multiple method names. (The #run method meant we needed tons of little classes that were 90% boilerplate. Check the new node_stats command).
1. Intent is to refactor the commands directory to be a direct mirror of the web API. This will simplify automated stats shipping.

### Node Stats

* [x] stats.events.in | /_node/stats/events
* [x] stats.events.filtered | /_node/stats/events |
* [x] stats.events.out | /_node/stats/events |
* [x] stats.jvm.threads.count | /_node/stats/jvm |
* [x] stats.jvm.threads.peak_count | /_node/stats/jvm |
* [x] stats.process.open_file_descriptors | /_node/stats/process |
* [x] stats.process.peak_open_file_descriptors | /_node/stats/process |
* [x] stats.process.max_file_descriptors | /_node/stats/process |
* [x] stats.process.cpu.percent | /_node/stats/process/cpu |
* [x] stats.process.cpu.total_in_millis | /_node/stats/process/cpu |
* [x] stats.process.mem.total_virtual_in_bytes | /_node/stats/process/mem

### CODE REVIEW

File: logstash-core/spec/support/resource_dsl_methods.rb [hunk 1]
```diff
@@ -0,0 +1,47 @@
+module ResourceDSLMethods
```
Comment (purbon) [inline logstash-core/spec/support/resource_dsl_methods.rb]: should we keep this support class within the api directory?

Comment (andrewvc) [inline logstash-core/spec/support/resource_dsl_methods.rb]: I think so, only API stuff would use it.

File: logstash-core/lib/logstash/api/app.rb [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+require "cabin"
+require "logstash/json"
+require "helpers/app_helpers"
+require "app/service"
+require "app/command_factory"
+require "logstash/util/loggable"
+
+module LogStash::Api
+  class App
+
```
Comment (suyograo) [inline logstash-core/lib/logstash/api/app.rb]: blank lines?

File: logstash-core/lib/logstash/api/app_helpers.rb [hunk 3]
```diff
@@ -20,4 +20,8 @@ def as_boolean(string)
     return false  if string == false  || string.blank? || string =~ (/(false|f|no|n|0)$/i)
     raise ArgumentError.new("invalid value for Boolean: \"#{string}\"")
   end
+
+  def define_resource(commands)
+    # TODO: stuff
```
Comment (suyograo) [inline logstash-core/lib/logstash/api/app_helpers.rb]: remove this method?

File: logstash-core/lib/logstash/api/app.rb (hunk 2 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/api/app.rb]: I'll just pull this class. I'm realizing now that it no longer has a purpose.

**Comment by andrewvc** [comment]
Thanks for the review @suyograo I've fixed those issues.

Tests won't pass without the master version of https://github.com/elastic/jrmonitor

I'm of the opinion that we should just pull it into the main Logstash repo. I think it's too much effort to maintain it as a separate gem.

File: logstash-core/lib/logstash/webserver.rb [hunk 4]
```diff
@@ -59,40 +56,34 @@ def error(str)
...
+        run LogStash::Api::Modules::Root
+        namespaces.each_pair do |namespace, app|
+          map(namespace) do
+            run app
+          end
+        end
+      end
+    end
+
+    def rack_namespaces
```
Comment (purbon) [inline logstash-core/lib/logstash/webserver.rb]: why should the webserver class care about the resources (web endpoints) defined in the webapp? for me having them here complicate the separation of concerns.

File: logstash-core/lib/logstash/webserver.rb [hunk 5]
```diff
@@ -31,24 +35,17 @@ def initialize(logger, options={})
...
     def run
       log "=== puma start: #{Time.now} ==="
 
-      @runner = Puma::Single.new(self)
-      @status = :run
-      @runner.run
-      stop(:graceful => true)
+      stop # Just in case
+
+      @server = ::Puma::Server.new rack_app
```
Comment (andrewvc) [inline logstash-core/lib/logstash/webserver.rb]: Check that in the future we could adjust thread settings

File: logstash-core/lib/logstash/api/modules/base.rb [hunk 6]
```diff
@@ -0,0 +1,41 @@
+require "logstash/api/app_helpers"
+require "logstash/api/command_factory"
+
+module LogStash
+  module Api
+    module Modules
+      class Base < ::Sinatra::Base
```
Comment (purbon) [inline logstash-core/lib/logstash/api/modules/base.rb]: I saw initially the modules as the resources (web api endpoints ) definition, base class should not be part of the modules as it does not really define web api resources. 

On the other side, just my experience and way of thinkings (does not have to be yours), but I like the idea of having a main app class, or file, in that case I guess we could for example move this base class to the the `logstash/api` directory, what do you think?

File: logstash-core/lib/logstash/util/thread_dump.rb [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+          i += 1
+        end
+      end
+
+      def idle_thread?(thread_name, data)
+        idle = false
+        if SKIPPED_THREADS.include?(thread_name)
+          # these are likely JVM dependent
+          idle = true
+        elsif thread_name.match(/Ruby-\d+-JIT-\d+/)
```
Comment (purbon) [inline logstash-core/lib/logstash/util/thread_dump.rb]: now that you're cleaning up, this is also welcome to clean up and aggregate somehow, what do you think?

File: logstash-core/lib/logstash/webserver.rb (hunk 4 above)
Comment (purbon) [inline logstash-core/lib/logstash/webserver.rb]: as spoken, this might also be part of the main app class, what do you think?

File: logstash-core/lib/logstash/api/commands/stats.rb [hunk 8]
```diff
@@ -0,0 +1,105 @@
+require "logstash/api/commands/base"
+require 'logstash/util/thread_dump'
+
+module LogStash
+  module Api
+    module Commands
+      class Stats < ::LogStash::Api::Commands::Base
```
Comment (purbon) [inline logstash-core/lib/logstash/api/commands/stats.rb]: why using full namespace here? if location is already scope, right?

**Comment by purbon** [comment]
I guess this PR might need a rebase.

File: logstash-core/lib/logstash/agent.rb [hunk 9]
```diff
@@ -17,6 +17,8 @@
 
 LogStash::Environment.load_locale!
 
+AGENT_LIST = {}
```
Comment (purbon) [inline logstash-core/lib/logstash/agent.rb]: Where is used?

**Comment by purbon** [comment]
@andrewvc as spoken, I gave a round of comments, assigning this back to you to follow up on them. Let  me know when all is up and I will review again 👍

File: logstash-core/lib/logstash/agent.rb (hunk 9 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/agent.rb]: Good call! This was left in from debugging some resource issues. Will remove :)

File: logstash-core/lib/logstash/api/commands/stats.rb (hunk 8 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/api/commands/stats.rb]: Yep, this can be shortened. I'll just make it 'Commands::Base' because 'Base' is so generic it can be a little confusing.

File: logstash-core/lib/logstash/api/modules/base.rb (hunk 6 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/api/modules/base.rb]: Well, I think its fairly common to have a 'base' class that's a sibling to the classes that inherit from it.

If we move it up a level it'd have to be renamed to `LogStash::Api::BaseModule` and moved to `api/base_module.rb`.

I'm fine with either approach. I take it you prefer the latter?

File: logstash-core/lib/logstash/util/thread_dump.rb (hunk 7 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/util/thread_dump.rb]: Makes sense, however, I think the scope has already blown up quite a bit, I'd rather do that in a separate PR.

File: logstash-core/lib/logstash/webserver.rb (hunk 4 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/webserver.rb]: I'll extract this out to a separate class for sure :)

**Comment by andrewvc** [comment]
@purbon I believe I have addressed all your PR feedback. How's it look now?

File: logstash-core/lib/logstash/agent.rb (hunk 9 above)
Comment (purbon) [inline logstash-core/lib/logstash/agent.rb]: still not removed, 👍  guess you miss the poor kid here :-P

File: logstash-core/lib/logstash/api/modules/base.rb (hunk 6 above)
Comment (purbon) [inline logstash-core/lib/logstash/api/modules/base.rb]: well, in that case for me (in my head) this is more like a utility base class, right? so ... let me explain. by having this and the actual resources in separate location we could achieve a more clear separation of concerns, right? I say that because end of the day, there is no actual resource setup with this class. What do you think?

File: logstash-core/lib/logstash/api/modules/node.rb [hunk 10]
```diff
@@ -0,0 +1,30 @@
+# encoding: utf-8
+module LogStash
+  module Api
+    module Modules
+      class Node < ::LogStash::Api::Modules::Base
+        get "/" do
+          payload = {
```
Comment (purbon) [inline logstash-core/lib/logstash/api/modules/node.rb]: can we might, use `payload = {}`

Comment (purbon) [inline logstash-core/lib/logstash/api/modules/node.rb]: also, now that I think about it, this resource looks empty to me, why is like this?

File: logstash-core/lib/logstash/api/rack_app.rb [hunk 11]
```diff
@@ -0,0 +1,32 @@
...
+            end
+          end
+        end
+      end
+
+      def self.rack_namespaces
+        {
+          "/_node" => LogStash::Api::Modules::Node,
+          "/_node/stats" => LogStash::Api::Modules::NodeStats,
+          "/_plugins" => LogStash::Api::Modules::Plugins
```
Comment (purbon) [inline logstash-core/lib/logstash/api/rack_app.rb]: why is module stats not used here? see https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/api/init.ru#L22-L25 as the current namespaces definitions.

File: logstash-core/lib/logstash/instrument/metric_store.rb [hunk 12]
```diff
@@ -100,6 +100,10 @@ def get(*key_paths)
       new_hash
     end
 
+    def get_shallow(*key_paths)
```
Comment (purbon) [inline logstash-core/lib/logstash/instrument/metric_store.rb]: can we add a comment here indicating what this function actually does?

File: logstash-core/lib/logstash/output_delegator.rb [hunk 13]
```diff
@@ -180,6 +180,6 @@ def worker_count
   end
 
   private
-  # Needed for testing, so private
+0  # Needed for testing, so private
```
Comment (purbon) [inline logstash-core/lib/logstash/output_delegator.rb]: why is a `0` added here before the comment, is this a typo probably?

File: logstash-core/lib/logstash/util/thread_dump.rb (hunk 7 above)
Comment (purbon) [inline logstash-core/lib/logstash/util/thread_dump.rb]: no problem, 👍

File: logstash-core/lib/logstash/webserver.rb [hunk 14]
```diff
@@ -31,24 +30,17 @@ def initialize(logger, options={})
...
     def run
       log "=== puma start: #{Time.now} ==="
 
-      @runner = Puma::Single.new(self)
-      @status = :run
-      @runner.run
-      stop(:graceful => true)
+      stop # Just in case
+
+      @server = ::Puma::Server.new(LogStash::Api::RackApp.app)
```
Comment (purbon) [inline logstash-core/lib/logstash/webserver.rb]: now looks awesome!!! 👍

File: logstash-core/spec/api/lib/api/node_stats_spec.rb [hunk 15]
```diff
@@ -1,68 +1,43 @@
...
 require "logstash/json"
 
-describe LogStash::Api::NodeStats do
-
+describe LogStash::Api::Modules::NodeStats do
   include Rack::Test::Methods
+  extend ResourceDSLMethods
 
-  def app()
+  def app() # Used by Rack::Test::Methods
```
Comment (purbon) [inline logstash-core/spec/api/lib/api/node_stats_spec.rb]: might be have this comment in line 10?

**Comment by purbon** [comment]
@andrewvc good work, It looks much better, I just left you a set of new comments, some minor, but some important ones to arrange somehow. see:

* https://github.com/elastic/logstash/pull/5307#discussion_r64537711
* https://github.com/elastic/logstash/pull/5307#discussion_r64537096
* https://github.com/elastic/logstash/pull/5307#discussion_r64536031

A typo:

* https://github.com/elastic/logstash/pull/5307#discussion_r64537984


re https://github.com/elastic/logstash/pull/5307#discussion_r64245604 I explained my way of thinkig about it, might I'm good to discuss with you, my raw motivation here is to have separated resource (api end points) definition from actually sinatra code setup.

happy to help,

- purbon

File: logstash-core/lib/logstash/output_delegator.rb (hunk 13 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/output_delegator.rb]: Ahhhh, good catch. Total typo.

File: logstash-core/lib/logstash/api/modules/node.rb (hunk 10 above)
Comment (andrewvc) [inline logstash-core/lib/logstash/api/modules/node.rb]: My mistake, I was partway through working on this and forgot about it. Will fix it up.

**Comment by purbon** [comment]
As spoken @andrewvc, If  all comments from https://github.com/elastic/logstash/pull/5307#issuecomment-221515453 are addresses, except the https://github.com/elastic/logstash/pull/5307#discussion_r64245604 that we know is a complicated story 👍 , I'm good to get it merged, so pre LGTM!! :shipit: :shipit:

**Comment by suyograo** [comment]
Jenkins, please test this.
