### PR TITLE
[Bugfix] Resolve the array and char (single | double quote) escaped values of ${ENV}

### LINKED ISSUE #16200: 8.14.0 xpack.management.pipeline.id * no longer working
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
2. 8.14.0
3. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
4.  docker.elastic.co/logstash/logstash:8.14.0
5. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
6. kubernetes

**OS version** (`uname -a` if on a Unix-like system): K8S 1.26.13

**Description of the problem including expected versus actual behavior**:
After upgrading from 8.13.0 to 8.14.0 logstash fails to start 

**Steps to reproduce**:
1. add the below configuration in logstash.yml to:
```
xpack.management.pipeline.id:
- '*'
```

**Provide logs (if relevant)**:
```
ERROR: Pipeline id in `xpack.management.pipeline.id` must begin with a letter or underscore and contain only letters, underscores, dashes, and numbers. The asterisk wildcard `*` can also be used. Invalid ids: ["*"]
usage:
  bin/logstash -f CONFIG_PATH [-t] [-r] [] [-w COUNT] [-l LOG]
  bin/logstash --modules MODULE_NAME [-M "MODULE_NAME.var.PLUGIN_TYPE.PLUGIN_NAME.VARIABLE_NAME=VALUE"] [-t] [-w COUNT] [-l LOG]
  bin/logstash -e CONFIG_STR [-t] [--log.level fatal|error|warn|info|debug|trace] [-w COUNT] [-l LOG]
  bin/logstash -i SHELL [--log.level fatal|error|warn|info|debug|trace]
  bin/logstash -V [--log.level fatal|error|warn|info|debug|trace]
  bin/logstash --help
[2024-06-06T11:35:47,812][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:921) ~[jruby.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:880) ~[jruby.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:90) ~[?:?]

```

### PR DESCRIPTION
**Pull request by mashhurs**
## Release notes

A bug (introduced in 8.13.1) fix to use array value with docker environment variables (such as `XPACK_MANAGEMENT_PIPELINE_ID`, `XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS`).

## What does this PR do?
Fixes the bug introduced by #16026. After 8.13.1, running Logstash on docker with list environment variable (example: `-e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS='[es.host.1, es.host.2:9500]'`) doesn't work. Current change fixes this issue.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files (and/or docker env variables)
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally
- run `rake artifact:docker` to build docker image
- use the hash value created by rake and replace `b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874` with your hash value

- ENV var carries list:

```
docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID="['*']" -e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS="['https://es1:9200', 'https://es2:9200']" -e XPACK_MONITORING_ENABLED=false sha256:b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874

docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID='["*"]' -e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS='["https://es1:9200", "https://es2:9200"]' -e XPACK_MONITORING_ENABLED=false b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874
```

- ENV var carries single value:
```
docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID="*" -e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS="https://es1:9200" -e XPACK_MONITORING_ENABLED=false b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874

docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID='*' -e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS='https://es1:9200' -e XPACK_MONITORING_ENABLED=false -it b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874

docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID="'*'" -e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS="https://es1:9200" -e XPACK_MONITORING_ENABLED=false -it b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874
			
docker run --rm --name=local-ls-docker -p 9600:9600 -e API_ENABLED=true -e XPACK_MANAGEMENT_ENABLED=true -e XPACK_MANAGEMENT_PIPELINE_ID='"*"' -e XPACK_MANAGEMENT_ELASTICSEARCH_HOSTS="https://es1:9200" -e XPACK_MONITORING_ENABLED=false -it b6c644b81357d29d9ae30b788fad327ece26d363c3541e566c543dc9dc084874
```

- To run docker acceptance test, use following commands
```
./gradlew clean bootstrap assemble installDefaultGems && rake artifact:docker
cd qa
bundle install
# make sure docker engine is running
bundle exec rspec docker/spec/full/container_spec.rb
```

## Related issues

- Closes #16200

### CODE REVIEW

File: logstash-core/lib/logstash/util/substitution_variables.rb [hunk 1]
```diff
@@ -76,6 +79,19 @@ def replace_placeholders(value)
...
+
+    # no further action need if substitution didn't happen
+    return placeholder_value unless is_placeholder_found
+
+    # ENV ${var} value may carry single quote or escaped double quote
+    # or single/double quoted entries in array string, needs to be refined
+    refined_value = placeholder_value.gsub(/[\\"\\']/, '')
+    if refined_value.start_with?('[') && refined_value.end_with?(']')
+      string_array = refined_value[1..-2] # removes the covered [] bracket
+      string_array.include?(',') ? string_array.split(',').map(&:strip) : string_array
```
Comment (jsvd) [inline logstash-core/lib/logstash/util/substitution_variables.rb:91]: We can be a little more resilient here to whitespace and simplify the code with something like:


```suggestion
    refined_value = placeholder_value.strip.gsub(/[\\"\\']/, '')
    if refined_value.start_with?('[') && refined_value.end_with?(']')
      # remove square brackets, split by comma and cleanup leading/trailing whitespace
      refined_value[1..-2].split(',').map(&:strip)
```

Comment (mashhurs) [reply logstash-core/lib/logstash/util/substitution_variables.rb]: It seems `placeholder_value.strip` breaks the agreement in config mixin: https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/1365#01911409-bfda-404f-a783-62b3574cef38

```

1) LogStash::Config::Mixin environment variable evaluation when an environment variable is not set and a default is given should use the default
--
  | Failure/Error: expect(subject.oneArray).to(be == ["first array value", "foo", "", " ", "foo bar"])
  |  
  | expected: == ["first array value", "foo", "", " ", "foo bar"]
  | got:    ["first array value", "foo", "", "", "foo bar"]
  | # ./logstash-core/spec/logstash/config/mixin_spec.rb:536:in `block in <main>'

```

**Comment by mashhurs** [comment]
Kicked off exhaustive CI: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/668

File: logstash-core/lib/logstash/util/substitution_variables.rb [hunk 2]
```diff
@@ -76,6 +79,19 @@ def replace_placeholders(value)
       end
       replacement.to_s
     end
+
+    # no further action need if substitution didn't happen
+    return placeholder_value unless is_placeholder_found
+
+    # ENV ${var} value may carry single quote or escaped double quote
+    # or single/double quoted entries in array string, needs to be refined
+    refined_value = placeholder_value.gsub(/[\\"\\']/, '')
```
Comment (jsvd) [inline logstash-core/lib/logstash/util/substitution_variables.rb:88]: I'd suggest trimming whitespace before and after the brackets, so that `start_with` and `end_with` can work with strings like `' ["a", "b", "c"] '`

Comment (jsvd) [inline logstash-core/lib/logstash/util/substitution_variables.rb:88]: I'd suggest trimming whitespace before and after the brackets, so that `start_with` and `end_with` can work with strings like `' ["a", "b", "c"] '`:

```suggestion
    refined_value = placeholder_value.strip.gsub(/[\\"\\']/, '')
```

Comment (mashhurs) [reply logstash-core/lib/logstash/util/substitution_variables.rb:88]: We have a [test case in config-mixin](https://github.com/elastic/logstash/blob/main/logstash-core/spec/logstash/config/mixin_spec.rb#L536) where it expects not to strip. We need to update test case (wonder what side affects would be) if this will be a strict requirement.

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by mashhurs** [comment]
@logstashmachine backport 8.15
