### PR TITLE
Fix reload of pipelines via `SIGHUP`

### LINKED ISSUE #13993: logstash process restarted after SIGHUP
**Logstash information**:
1. Logstash 7.11.2 and onwards, not tested on v8
2. Logstash installation source - .deb
3. How is Logstash being run - systemd

**Plugins installed**:
logstash-codec-avro (3.2.4)
logstash-codec-cef (6.1.1)
logstash-codec-collectd (3.0.8)
logstash-codec-dots (3.0.6)
logstash-codec-edn (3.0.6)
logstash-codec-edn_lines (3.0.6)
logstash-codec-es_bulk (3.0.8)
logstash-codec-fluent (3.3.0)
logstash-codec-graphite (3.0.5)
logstash-codec-json (3.0.5)
logstash-codec-json_lines (3.0.6)
logstash-codec-line (3.0.8)
logstash-codec-msgpack (3.0.7)
logstash-codec-multiline (3.0.10)
logstash-codec-netflow (4.2.1)
logstash-codec-plain (3.0.6)
logstash-codec-rubydebug (3.1.0)
logstash-filter-aggregate (2.9.1)
logstash-filter-anonymize (3.0.6)
logstash-filter-cidr (3.1.3)
logstash-filter-clone (4.0.0)
logstash-filter-csv (3.0.10)
logstash-filter-date (3.1.9)
logstash-filter-de_dot (1.0.4)
logstash-filter-dissect (1.2.0)
logstash-filter-dns (3.1.4)
logstash-filter-drop (3.0.5)
logstash-filter-elasticsearch (3.9.3)
logstash-filter-fingerprint (3.2.2)
logstash-filter-geoip (6.0.5)
logstash-filter-grok (4.3.0)
logstash-filter-http (1.0.2)
logstash-filter-json (3.1.0)
logstash-filter-kv (4.4.1)
logstash-filter-memcached (1.1.0)
logstash-filter-metrics (4.0.7)
logstash-filter-mutate (3.5.0)
logstash-filter-prune (3.0.4)
logstash-filter-ruby (3.1.5)
logstash-filter-sleep (3.0.7)
logstash-filter-split (3.1.8)
logstash-filter-syslog_pri (3.0.5)
logstash-filter-throttle (4.0.4)
logstash-filter-translate (3.2.3)
logstash-filter-truncate (1.0.4)
logstash-filter-urldecode (3.0.6)
logstash-filter-useragent (3.2.4)
logstash-filter-uuid (3.0.5)
logstash-filter-xml (4.1.1)
logstash-input-azure_event_hubs (1.2.3)
logstash-input-beats (6.0.14)
logstash-input-couchdb_changes (3.1.6)
logstash-input-dead_letter_queue (1.1.5)
logstash-input-elasticsearch (4.9.1)
logstash-input-exec (3.3.3)
logstash-input-file (4.2.3)
logstash-input-ganglia (3.1.4)
logstash-input-gelf (3.3.0)
logstash-input-generator (3.0.6)
logstash-input-graphite (3.0.6)
logstash-input-heartbeat (3.0.7)
logstash-input-http (3.3.7)
logstash-input-http_poller (5.0.2)
logstash-input-imap (3.1.0)
logstash-input-jms (3.1.2)
logstash-input-pipe (3.0.7)
logstash-input-redis (3.5.1)
logstash-input-s3 (3.5.0)
logstash-input-snmp (1.2.7)
logstash-input-snmptrap (3.0.6)
logstash-input-sqs (3.1.3)
logstash-input-stdin (3.2.6)
logstash-input-syslog (3.4.5)
logstash-input-tcp (6.0.7)
logstash-input-twitter (4.0.3)
logstash-input-udp (3.3.4)
logstash-input-unix (3.0.7)
logstash-integration-jdbc (5.0.6)
 ├── logstash-input-jdbc
 ├── logstash-filter-jdbc_streaming
 └── logstash-filter-jdbc_static
logstash-integration-kafka (10.7.1)
 ├── logstash-input-kafka
 └── logstash-output-kafka
logstash-integration-rabbitmq (7.1.1)
 ├── logstash-input-rabbitmq
 └── logstash-output-rabbitmq
logstash-output-cloudwatch (3.0.9)
logstash-output-csv (3.0.8)
logstash-output-elastic_app_search (1.1.1)
logstash-output-elasticsearch (10.8.4)
logstash-output-email (4.1.1)
logstash-output-file (4.3.0)
logstash-output-graphite (3.1.6)
logstash-output-http (5.2.4)
logstash-output-lumberjack (3.1.8)
logstash-output-nagios (3.0.6)
logstash-output-null (3.0.5)
logstash-output-opensearch (1.2.0)
logstash-output-pipe (3.0.6)
logstash-output-redis (5.0.0)
logstash-output-s3 (4.3.3)
logstash-output-sns (4.0.7)
logstash-output-sqs (6.0.0)
logstash-output-stdout (3.1.4)
logstash-output-tcp (6.0.0)
logstash-output-udp (3.1.0)
logstash-output-webhdfs (3.0.6)
logstash-patterns-core (4.1.2)

**JVM** :
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

**OS version**:
Linux logstashd 5.4.0-1071-aws #76~18.04.1-Ubuntu SMP Mon Mar 28 17:49:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
After issuing a SIGHUP signal in order to reload the pipeline the pipeline is reloaded after which a full restart of Logstash service is executed. 

The release notes of 7.11.2 describe a fix being made to address an issue with reloading pipelines. See the related issue https://github.com/elastic/logstash/pull/12444

**Steps to reproduce**:
 1. Start a Logstash process running any version between 7.11.2-7.17.2
 2. Make some changes to the pipeline configurations 
 3. send a SIGHUP signal to the Logstash process (pkill -1 -u logstash)

**Provide logs (if relevant)**:
[2022-04-13T11:34:13,239][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
-- redacted --
[2022-04-13T11:42:21,790][WARN ][logstash.runner          ] SIGHUP received.
-- redacted --
[2022-04-13T11:42:33,729][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:main}
[2022-04-13T11:42:51,084][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{}}
[2022-04-13T11:42:51,100][ERROR][org.logstash.execution.ShutdownWatcherExt] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2022-04-13T11:42:56,112][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{}}
[2022-04-13T11:43:01,121][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{}}
[2022-04-13T11:43:06,131][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{}}
[2022-04-13T11:43:09,915][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
-- redacted --
[2022-04-13T11:43:20,356][INFO ][logstash.outputs.opensearch][main] Cluster version determined (7.10.2) {:version=>7}
[2022-04-13T11:43:21,804][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>250, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>500, "pipeline.sources"=>["/etc/logstash/conf.d/01-lumberjack-input.conf", "/etc/logstash/conf.d/02-fluent-bit.conf", "/etc/logstash/conf.d/50-lumberjack-output.conf"], :thread=>"#<Thread:0x7a2c6633 run>"}
[2022-04-13T11:43:24,328][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>2.52}
[2022-04-13T11:43:24,333][INFO ][logstash.inputs.beats    ][main] Starting input listener {:address=>"0.0.0.0:5003"}
[2022-04-13T11:43:24,515][INFO ][logstash.inputs.s3       ][main] Registering {:bucket=>"", :region=>"eu-central-1"}
[2022-04-13T11:43:24,605][INFO ][logstash.inputs.s3       ][main] Registering {:bucket=>"", :region=>"eu-central-1"}
[2022-04-13T11:43:24,661][INFO ][logstash.inputs.beats    ][main] Starting input listener {:address=>"0.0.0.0:5001"}
[2022-04-13T11:43:24,743][INFO ][logstash.inputs.s3       ][main] Registering {:bucket=>"", :region=>"us-east-1"}
[2022-04-13T11:43:24,767][INFO ][logstash.inputs.s3       ][main] Registering {:bucket=>"", :region=>"eu-central-1"}
[2022-04-13T11:43:24,905][INFO ][org.logstash.beats.Server][main][bdc12cad881a5efe46515fd0703cd0842fa371fb2d6d038c55532f6180481d47] Starting server on port: 5003
[2022-04-13T11:43:24,962][INFO ][org.logstash.beats.Server][main][a7a4e16874d31e612e1f23d0bf0f971cb83bbfe760be18ce290f364517cba441] Starting server on port: 5001
[2022-04-13T11:43:24,967][INFO ][logstash.inputs.syslog   ][main][540e566fefdee2f82720ded76bcee7c4f4f9dd53bd893251dc82cfc91a58cc8f] Starting syslog udp listener {:address=>"0.0.0.0:5002"}
[2022-04-13T11:43:24,949][INFO ][logstash.inputs.syslog   ][main][540e566fefdee2f82720ded76bcee7c4f4f9dd53bd893251dc82cfc91a58cc8f] Starting syslog tcp listener {:address=>"0.0.0.0:5002"}
[2022-04-13T11:43:25,000][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2022-04-13T11:43:24,965][INFO ][logstash.inputs.http     ][main][e9346dc9d69fb785accc5e759f3c5b424e31526e6803446ca10ea53a535a24b0] Starting http input listener {:address=>"0.0.0.0:5004", :ssl=>"false"}
[2022-04-13T11:43:24,998][INFO ][logstash.inputs.http     ][main][7e68ae3c0486e02c85ea536d0f68783763c56a6943163c84cc8eb56b424116ca] Starting http input listener {:address=>"0.0.0.0:5005", :ssl=>"true"}
[2022-04-13T11:43:25,121][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2022-04-13T11:43:40,378][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2022-04-13T11:43:41,481][INFO ][logstash.runner          ] Logstash shut down.

### PR DESCRIPTION
**Pull request by robbavey**
When logstash is run without automatic reloading, it is still possible to reload configurations
by using 'SIGHUP'. This functionality was broken in #12444, which split non-terminated pipelines
into "loading" and "running" states. The call `no_pipelines?` in agent#execute would no longer
find pipelines in a "loading" state, causing the loop to exit, and logstash to shutdown. This
commit tests for pipelines in a "loading" state to restore functionality

## Release notes
Fix support for reload of pipelines via `SIGHUP`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## How to test this PR locally

- Run Logstash with `config.reload.automatic` set to `false
- Update pipeline configuration
- `kill -1 <pid>`
- Note that pipeline reloads and logstash stays running

## Related issues

- Closes #13993

### CODE REVIEW

**Review by jsvd — APPROVED** [review]
LGTM, good catch. Thanks for tweaking the test to catch this.

**Comment by jsvd** [comment]
@robbavey the test failure seems unrelated, but please open a "test-failure" issue with the stack traces so we can track it.

**Comment by robbavey** [comment]
@jsvd - yes, looking at the history of that test failure, it predates this PR. I'll create an issue

File: logstash-core/lib/logstash/agent.rb [hunk 1]
```diff
@@ -314,7 +314,7 @@ def running_user_defined_pipelines
   end
 
   def no_pipeline?
-    @pipelines_registry.running_pipelines.empty?
+    @pipelines_registry.running_pipelines.empty? && @pipelines_registry.loading_pipelines.empty?
```
Comment (yaauie) [inline logstash-core/lib/logstash/agent.rb:317]: @robbavey I know this is a little late post-merge, but a pipeline that transitions from `loading` to `running` while this is being executed can miss both clauses.

The following should provide us some additional safety:

~~~ diff
diff --git a/logstash-core/lib/logstash/agent.rb b/logstash-core/lib/logstash/agent.rb
index 701dfec56..2d0598ecc 100644
--- a/logstash-core/lib/logstash/agent.rb
+++ b/logstash-core/lib/logstash/agent.rb
@@ -314,7 +314,7 @@ class LogStash::Agent
   end
 
   def no_pipeline?
-    @pipelines_registry.running_pipelines.empty?
+    @pipelines_registry.running_pipelines(include_loading: true).empty?
   end
 
   private
diff --git a/logstash-core/lib/logstash/pipelines_registry.rb b/logstash-core/lib/logstash/pipelines_registry.rb
index 20186775b..53dc112a3 100644
--- a/logstash-core/lib/logstash/pipelines_registry.rb
+++ b/logstash-core/lib/logstash/pipelines_registry.rb
@@ -24,8 +24,8 @@ module LogStash
       @pipeline = pipeline
       @loading = Concurrent::AtomicBoolean.new(false)
 
-      # this class uses a lock to ensure thread safe visibility.
-      @lock = Mutex.new
+      # this class uses a reentrant lock to ensure thread safe visibility.
+      @lock = Monitor.new
     end
 
     def terminated?
@@ -64,6 +64,12 @@ module LogStash
     def pipeline
       @lock.synchronize { @pipeline }
     end
+
+    def synchronize
+      @lock.synchronize do
+        yield self
+      end
+    end
   end
 
   class PipelineStates
@@ -265,8 +271,8 @@ module LogStash
     end
 
     # @return [Hash{String=>Pipeline}]
-    def running_pipelines
-      select_pipelines { |state| state.running? }
+    def running_pipelines(include_loading: false)
+      select_pipelines { |state| state.running? || (include_loading && state.loading?) }
     end
 
     def loading_pipelines
@@ -296,7 +302,7 @@ module LogStash
     # @return [Hash{String=>Pipeline}]
     def select_pipelines(&optional_state_filter)
       @states.each_with_object({}) do |(id, state), memo|
-        if state && (!block_given? || yield(state))
+        if state && (!block_given? || state.synchronize(&optional_state_filter))
           memo[id] = state.pipeline
         end
       end
~~~

**Comment by kaisecheng** [comment]
@logstashmachine backport 7.17

**Comment by kaisecheng** [comment]
@logstashmachine backport 8.2
