### PR TITLE
[DRA] Avoid to loose err code on docker save

### LINKED ISSUE #14776: [automation] DRA fail to export ARM64 Docker images doesn't fail the Jenkins job
It happened once (maybe more times, but not recognized) that DRA scripts create docker images tar.gz almost empty.

In run https://logstash-ci.elastic.co/job/elastic+logstash+8.6+multijob-dra-docker-aarch64/8/console
was created small `tar.gz` and looking at Jenkins console output, the error response from Docker daemon didn't fail the bash script.

```bash
INFO: Build complete, setting STACK_VERSION to 8.6.0.
INFO: Saving tar.gz for docker images
Error response from daemon: reference does not exist
Error response from daemon: reference does not exist
Error response from daemon: reference does not exist
INFO: GENERATED ARTIFACTS
8d0a12b4cbf08eb2d69b15c7fb698f23ef93df65  build/logstash-8.6.0-darwin-aarch64.tar.gz
7514c17f3f871335200f8dd386d5cc1966578d90  build/logstash-8.6.0-darwin-x86_64.tar.gz
3df61dff32c7276d2c9da1c3cf987f28098ab2c9  build/logstash-8.6.0-docker-image-aarch64.tar.gz
68bcede9646236ec7a1e9a6f58f00da56e621814  build/logstash-8.6.0-linux-aarch64.tar.gz
9d171ef35e7faff1c80cc2e5728c107c1da9ba3d  build/logstash-8.6.0-linux-x86_64.tar.gz
245c0b3af20525204ea7d01e6820bb895976f314  build/logstash-8.6.0-no-jdk.tar.gz
a8f8384ee71d9608fb65170809ba56cecb266d14  build/logstash-8.6.0-no-jdk.zip
bc4537346fd1b395d2fc16709b5637b7f710dc76  build/logstash-8.6.0-windows-x86_64.zip
19d05dcf5dd5901169f5b06fbbab2311cfdfb45b  build/logstash-ironbank-8.6.0-docker-build-context.tar.gz
018e4d0a828b35022326ee267e4e5a6a726c5c2f  build/logstash-oss-8.6.0-darwin-aarch64.tar.gz
661f587fc499782fcd466af8cbcfab18a8621b1e  build/logstash-oss-8.6.0-darwin-x86_64.tar.gz
3df61dff32c7276d2c9da1c3cf987f28098ab2c9  build/logstash-oss-8.6.0-docker-image-aarch64.tar.gz
8dc91804ecf004328c83bdfa13de2450aa19cf1d  build/logstash-oss-8.6.0-linux-aarch64.tar.gz
0d9f2bdf51cf8160f5d50ee1f9dfa87e70c1e726  build/logstash-oss-8.6.0-linux-x86_64.tar.gz
368a46a21b56401fd5884fa9bc6ec6cf8b554220  build/logstash-oss-8.6.0-no-jdk.tar.gz
1d1546dec41abfcbc7d94901f44c9fda3c195bdc  build/logstash-oss-8.6.0-no-jdk.zip
9915462166c6731bd7fd221a27d6f0c51eee40bb  build/logstash-oss-8.6.0-windows-x86_64.zip
3df61dff32c7276d2c9da1c3cf987f28098ab2c9  build/logstash-ubi8-8.6.0-docker-image-aarch64.tar.gz
INFO: UPLOADING TO INTERMEDIATE BUCKET
INFO: Uploading build/logstash-8.6.0-docker-image-aarch64.tar.gz...
Copying [file://build/logstash-8.6.0-docker-image-aarch64.tar.gz](file:///logstash-8.6.0-docker-image-aarch64.tar.gz) [Content-Type=application/x-tar]...
/ [0 files][    0.0 B/   20.0 B]                                                
/ [1 files][   20.0 B/   20.0 B]                                                
Operation completed over 1 objects/20.0 B.                                       
INFO: Uploading build/logstash-oss-8.6.0-docker-image-aarch64.tar.gz...
Copying [file://build/logstash-oss-8.6.0-docker-image-aarch64.tar.gz](file:///logstash-oss-8.6.0-docker-image-aarch64.tar.gz) [Content-Type=application/x-tar]...
/ [0 files][    0.0 B/   20.0 B]                                                
/ [1 files][   20.0 B/   20.0 B]                                                
Operation completed over 1 objects/20.0 B.                                       
INFO: Uploading build/logstash-ubi8-8.6.0-docker-image-aarch64.tar.gz...
Copying [file://build/logstash-ubi8-8.6.0-docker-image-aarch64.tar.gz](file:///logstash-ubi8-8.6.0-docker-image-aarch64.tar.gz) [Content-Type=application/x-tar]...
/ [0 files][    0.0 B/   20.0 B]                                                
/ [1 files][   20.0 B/   20.0 B]                                                
Operation completed over 1 objects/20.0 B.
```

Quite similar, as net result, to #14702

cc @mgreau @roaksoax

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

[rn:skip] 

## What does this PR do?

Avoid to pipe the output of `docker save` to `gzip` because if docker save terminates with error code 2 and its stdout has the value:
```
Error response from daemon: reference does not exist
```
This command generated a gzip file with the content above and error code set to 0.
This commit uses the `-o` option of `docker save` to avoid using stdout and in case of exit code other than 0, exit the bash script immediately.

## Why is it important/What is the impact to the user?

As a release manager I want that any intermediate command that has non zero exit code terminate immediately the bash script.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## How to test this PR locally

With the command:
```bash
docker save "docker.elastic.co/logstash/logstash-ubi8:8.6.0" | gzip -c > "/tmp/logstash-ubi8-8.6.0-docker-image-x86.tar.gz"
```
the exit code `$?` is  0 and the file 
```
/tmp/logstash-ubi8-8.6.0-docker-image-x86.tar.gz
```
contains the zipped 
```
Error response from daemon: reference does not exist
```

## Related issues

- Fix #14776

### CODE REVIEW

File: ci/dra_common.sh [hunk 1]
```diff
@@ -11,7 +11,10 @@ function save_docker_tarballs {
     local arch="${1:?architecture required}"
     local version="${2:?stack-version required}"
     for image in logstash logstash-oss logstash-ubi8; do
-        docker save "docker.elastic.co/logstash/${image}:${version}" | gzip -c > "build/${image}-${version}-docker-image-${arch}.tar.gz"
+        docker save -o "build/${image}-${version}-docker-image-${arch}.tar.gz" "docker.elastic.co/logstash/${image}:${version}"
+        if [ $? != 0 ]
+            error "Hit a problem in saving the Docker image for ${image}"
```
Comment (roaksoax) [inline ci/dra_common.sh:16]: Unable to save the Docker image for ${image}. Aborting the image build process.

**Review by roaksoax — APPROVED** [review]

**Comment by andsel** [comment]
@logstashmachine backport 8.5

**Comment by andsel** [comment]
@logstashmachine backport 7.17
