### PR TITLE
DRA - Fix error reporting

### LINKED ISSUE #14697: DRA - building dockerfile fails, but script things it was successful.
A DRA job resulted in an error, but the script didn't report that as a failure, which resulted in Jenkins marking it successful.

The error seen was:

```
Downloading Python-3.6.13.tar.xz...
-> https://www.python.org/ftp/python/3.6.13/Python-3.6.13.tar.xz
Installing Python-3.6.13...

BUILD FAILED (Ubuntu 22.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20221025025205.31166
Results logged to /tmp/python-build.20221025025205.31166.log

Last 10 log lines:
	case upgrade in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Segmentation fault
make[1]: *** [Makefile:1102: install] Error 139
make[1]: Leaving directory '/tmp/python-build.20221025025205.31166/Python-3.6.13'
make: *** [Makefile:187: venv] Error 1
```

### PR DESCRIPTION
**Pull request by roaksoax**
When rake fails to build, the error doesn't seem to bubbled up all the way to script that calls it or Jenkins. This tries to workaround the issue.

Closes #14697

### CODE REVIEW

File: ci/dra_docker.sh [hunk 1]
```diff
@@ -26,16 +26,16 @@ case "$WORKFLOW_TYPE" in
         STACK_VERSION=${STACK_VERSION}-SNAPSHOT
         info "Build complete, setting STACK_VERSION to $STACK_VERSION."
         ;;
-    staging)
+    staging) || error "artifact:docker build failed."
```
Comment (robbavey) [inline ci/dra_docker.sh:29]: Copy paste error?
```suggestion
    staging)
```

**Review by robbavey — CHANGES_REQUESTED** [review]
I think there's a copy/paste error

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by roaksoax** [comment]
@logstashmachine backport 7.17

**Comment by roaksoax** [comment]
@logstashmachine backport 8.5
