### PR TITLE
verify available disk space for PQ.

### LINKED ISSUE #6552: Add bootstrap checks to persistent queue
When persistent queue is enabled, add the following bootstrap checks when starting LS

- [ ] validate if there is enough disk space to allocate at least page-size worth of data.
- [ ] ensure `queue.max_bytes` is available on disk.

 If these are not satisfied, Logstash should fail to start up.

### PR DESCRIPTION
**Pull request by colinsurprenant**
This is a reboot of #6998 originally by @original-brownbear.

Fixes #6552 

* Implemented free disk space check in Java
* Added JUnit test for the Java file system logic
* Added new bootstrap check to checks against the max of (`queue.max_bytes` and `queue.page_capacity`)
* `Queue.open()` will throw an exception if there is not enough disk space to allocate  `queue.max_bytes`  minus existing pages sizes.

### CODE REVIEW

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 1]
```diff
@@ -188,6 +194,7 @@ public void open() throws IOException {
                 } else {
                     pageIO.open(cp.getMinSeqNum(), cp.getElementCount());
                     addTailPage(cp, PageFactory.newTailPage(cp, this, pageIO));
+                    diskNeeded -= (long)pageIO.getHead();
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java]: for my own clarification:

Since we opened this PageIO with the checkpoint's element count, we skipped over that many items moving the head to the end of the file, so `PageIO#getHead()` should effectively return the filesize in bytes.

We are then subtracting the size of all existing non-fully-ack'd files from our `maxBytes` configuration; when we are done looking at all the pages, `diskNeeded` will represent the _remaining_ amount of disk space we're allowed to consume.

In this light, what we're doing makes sense.

File: logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java [hunk 2]
```diff
@@ -994,4 +1008,12 @@ public void maximizeBatch() throws IOException, InterruptedException, ExecutionE
             assertThat(b.size(), is(2));
         }
     }
+
+    @Test(expected = IOException.class)
+    public void throwsWhenNotEnoughDiskFree() throws Exception {
+        Settings settings = SettingsImpl.builder(TestSettings.persistedQueueSettings(100, dataPath)).queueMaxBytes(Long.MAX_VALUE).build();
```
Comment (yaauie) [inline logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java]: nitpick: the relevant bits of this test are way off to the right; a minor change in indentation allows us to bring them to the forefront and add useful commentary:

~~~diff
-        Settings settings = SettingsImpl.builder(TestSettings.persistedQueueSettings(100, dataPath)).queueMaxBytes(Long.MAX_VALUE).build();
+        Settings settings = SettingsImpl.builder(TestSettings.persistedQueueSettings(100, dataPath))
+                                        .queueMaxBytes(Long.MAX_VALUE) // ask for far too much disk
+                                        .build();
~~~

File: logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+require 'logstash/errors'
+
+module LogStash
+  module BootstrapCheck
+    class PersistedQueueConfig
+      def self.check(settings)
+        return unless settings.get('queue.type') == 'persisted'
+        if settings.get('queue.page_capacity') > settings.get('queue.max_bytes')
+          raise(LogStash::BootstrapCheckError, 'Invalid configuration, `queue.page_capacity` must be smaller or equal to `queue.max_bytes`')
+        end
```
Comment (yaauie) [inline logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb]: should we also check for available disk space in the bootstrap check, instead of waiting until we attempt to create a page?

File: logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb [hunk 4]
```diff
@@ -0,0 +1,15 @@
+# encoding: utf-8
+require 'logstash/errors'
+
+module LogStash
+  module BootstrapCheck
+    class PersistedQueueConfig
+      def self.check(settings)
+        return unless settings.get('queue.type') == 'persisted'
+        if settings.get('queue.page_capacity') > settings.get('queue.max_bytes')
+          raise(LogStash::BootstrapCheckError, 'Invalid configuration, `queue.page_capacity` must be smaller or equal to `queue.max_bytes`')
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb]: +1

File: logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb (hunk 3 above)
Comment (colinsurprenant) [reply logstash-core/lib/logstash/bootstrap_check/persisted_queue_config.rb]: not really because we need to take into account the existing queue data/state and this is computed in queue open. For example if max_bytes is 2GB but there is already 1GB of pages allocation then available disk space must be >= 1GB, not 2.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java (hunk 1 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java]: +1

File: logstash-core/src/main/java/org/logstash/common/FsUtil.java [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+     * @param path Directory to check
+     * @param size Bytes of free space requested
+     * @return True iff the
+     * @throws IOException on failure to determine free space for given path's partition
+     */
+    public static boolean hasFreeSpace(final String path, final long size) throws IOException {
+        final File[] partitions = File.listRoots();
+        File location = new File(path).getCanonicalFile();
+        boolean found = false;
+        while (!found) {
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/common/FsUtil.java]: <3

File: logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java (hunk 2 above)
Comment (colinsurprenant) [reply logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java]: +1

**Comment by colinsurprenant** [comment]
thanks @yaauie for the review. addressed your concerns, let me know how this looks.

**Comment by colinsurprenant** [comment]
rebased and fixed conflict, will wait on green before merging.

**Comment by colinsurprenant** [comment]
jenkins please test this

**Comment by colinsurprenant** [comment]
jenkins please test this

**Comment by colinsurprenant** [comment]
finally green, squashing and merging into master and 6.x

**Comment by colinsurprenant** [comment]
thanks @yaauie for the review!
