### PR TITLE
fix flushing upon empty batches with ordered execution

### LINKED ISSUE #12158: When java execution is enabled, periodic_flushers and shutdown_flushers are never called
An aggregate filter that uses push_map_as_event_on_timeout relies on flush being called regularly. This does not occur if java execution is enabled. Originally mentioned [here](https://discuss.elastic.co/t/new-way-in-which-java-execution-breaks-the-aggregate-filter/239377).

If java execution is disabled, then with this data
```
INFO - 12345 - Clicked One
INFO - 12345 - Clicked Two
INFO - 12345 - Clicked Three
```
and this configuration
```
input { stdin {} }
filter {
    grok { match => [ "message", "%{LOGLEVEL:loglevel} - %{NOTSPACE:user_id} - %{GREEDYDATA:msg_text}" ] }
    aggregate {
        task_id => "%{user_id}"
        code => "map['clicks'] ||= 0; map['clicks'] += 1;"
        push_map_as_event_on_timeout => true
        timeout_task_id_field => "user_id"
        timeout => 10
    }
}
output  { stdout { codec => rubydebug { metadata => false } } }
```
I get these messages
```
[2020-06-30T18:50:48,464][TRACE][logstash.filters.aggregate][main] Aggregate flush call with {:final=>false}
[2020-06-30T18:50:48,466][DEBUG][logstash.filters.aggregate][main] Aggregate remove_expired_maps call with '%{user_id}' pattern and 1 maps
[2020-06-30T18:50:48,487][DEBUG][logstash.filters.aggregate][main] Aggregate create_timeout_event call with task_id '12345'
[2020-06-30T18:50:48,513][DEBUG][logstash.filters.aggregate][main] Aggregate remove expired map with task_id=12345
```
and an event that looks like
```
{
   "user_id" => "12345",
    "clicks" => 3,
"@timestamp" => 2020-06-30T22:50:48.490Z,
  "@version" => "1"
}
```
If I enable java_execution then those messages disappear (the flush never occurs) and the map contents are never pushed.

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #12158
Reboot of #12196

When running a pipeline with ordered execution, flushes on the pipeline
were no longer being called when compute is called with an empty batch, causing
issues with the aggregate filter, for example, not being able to push events on
timeout.

This fix checks if the batch is empty and if a flush is required in which case compute on an empty batch is called for a flush operation to happen.

### CODE REVIEW

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 1]
```diff
@@ -306,23 +306,35 @@ private boolean isOutput(final Vertex vertex) {
...
+                // send batch one-by-one as single-element batches down the filters
+                for (final RubyEvent e : batch) {
+                    filterBatch.set(0, e);
+                    _compute(filterBatch, outputBatch, flush, shutdown);
+                }
+                compiledOutputs.compute(outputBatch, flush, shutdown);
+            } else if (flush) {
+                @SuppressWarnings({"unchecked"}) final RubyArray<RubyEvent> outputBatch = RubyUtil.RUBY.newArray();
+                _compute(EMPTY_ARRAY, outputBatch, true, shutdown);
+                compiledOutputs.compute(outputBatch, true, shutdown);
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java:330]:
```suggestion
            @SuppressWarnings({"unchecked"}) final RubyArray<RubyEvent> outputBatch = RubyUtil.RUBY.newArray();
            if (batch.isEmpty() && flush) {
                _compute(EMPTY_ARRAY, outputBatch, true, shutdown);
            } else {
                @SuppressWarnings({"unchecked"}) final RubyArray<RubyEvent> filterBatch = RubyUtil.RUBY.newArray(1);
                // send batch one-by-one as single-element batches down the filters
                for (final RubyEvent e : batch) {
                    filterBatch.set(0, e);
                    _compute(filterBatch, outputBatch, flush, shutdown);
                }
            }
            compiledOutputs.compute(outputBatch, flush, shutdown);
```

Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java:330]: Do think this could be more readable, extracting the head and tail common part of condition body?

**Review by andsel — APPROVED** [review]
LGTM, I've left a comment if you think that readability of the code could be improved, however you can merge as it currently is

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 1 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java:330]: This is what I had in the first place but realized that the `else` clause will catch the condition of `batch.isEmpty() == true && flush == false` which we don't really want so that's why I shuffled the condition to make that that upon an empty batch and no flush required, nothing happens.

Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java:330]: the `else` should catch `batch.isEmpty()==false || flush == false`

Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java:330]: but is LGTM, go with the merge for me

**Review by andsel — APPROVED** [review]
LGTM

**Comment by colinsurprenant** [comment]
@andsel Thanks for the review. I've just added a check for the shutdown condition which is eventually used to figure when a final flush is required. LMKWYT.

**Review by jsvd — APPROVED** [review]
LGTM, I managed to test it manually before and after

**Comment by colinsurprenant** [comment]
Thanks @andsel @jsvd ,merged, will be available starting in 7.9.1
