### PR TITLE
work around jruby-5642 during package installation on jdk11

### LINKED ISSUE #10593: Logstash 6.7 package from apt fails on Debian Buster
- Version: 1:6.7.0-1
- Operating System: Debian Buster
- Steps to Reproduce: install the logstash-1:6.7.0 package from artifacts.elastic.co , the post-install script fails:

```
Setting up logstash (1:6.7.0-1) ...
Using provided startup.options file: /etc/logstash/startup.options
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper$ReflectiveAccess to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper$ReflectiveAccess
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Errno::EBADF: Bad file descriptor - systemctl
            spawn at org/jruby/RubyProcess.java:1567
            spawn at org/jruby/RubyKernel.java:1632
        popen_run at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:206
           popen3 at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:102
          execute at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:74
   detect_systemd at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:29
  detect_platform at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:24
           detect at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:18
   setup_defaults at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:153
          execute at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:119
              run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
              run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:114
              run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
           <main> at /usr/share/logstash/lib/systeminstall/pleasewrap.rb:12
chmod: cannot access '/etc/default/logstash': No such file or directory
dpkg: error processing package logstash (--configure):
 installed logstash package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 logstash

```

I'm not yet 100% sure it's not something related to my global Java settings, if you can suggest additional debugging flags to pass to bin/system-install , I'd appreciate it.

### PR DESCRIPTION
**Pull request by jsvd**
This workaround is only executed during pkging tasks so doesn't influence normal execution.

fixes #10593

### CODE REVIEW

File: lib/systeminstall/pleasewrap.rb [hunk 1]
```diff
@@ -8,5 +8,25 @@
 
 #libdir = File.expand_path("../lib", File.dirname(__FILE__))
 #$LOAD_PATH << libdir if File.exist?(File.join(libdir, "pleaserun", "cli.rb"))
+
+require 'open3'
+
+# Work around for https://github.com/elastic/logstash/issues/10593
+# Issue on JRUBY https://github.com/jruby/jruby/issues/5642
+# Workaround retrieved from https://github.com/jruby/jruby/issues/5642#issuecomment-479671017
+if java.lang.System.getProperty("java.version").start_with?("11")
```
Comment (colinsurprenant) [inline lib/systeminstall/pleasewrap.rb]: I suggest we also add a condition on the JRuby version change so that if we update JRuby and forget to verify if this is still needed a least a build failure will direct us to take a look and either remove that or push back the check for the next JRuby version. WDYT?

Comment (jsvd) [reply lib/systeminstall/pleasewrap.rb]: Since there's no JRuby version fixed already and it's not guaranteed the next release will have a fix, what do you suggest to use as a condition here?

Comment (colinsurprenant) [reply lib/systeminstall/pleasewrap.rb]: if the version of JRuby is different than the one in use now then fail? that way if/when we upgrade JRuby it will force us to verify  if patch is still needed and then adjust in either cases, no?

Comment (colinsurprenant) [reply lib/systeminstall/pleasewrap.rb]: I am just trying to avoid keeping code around, especially monkey patches, that might not be needed at some point.

Comment (jsvd) [reply lib/systeminstall/pleasewrap.rb]: done:
```
# dpkg-reconfigure logstash
Using provided startup.options file: /etc/logstash/startup.options
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
RuntimeError: A workaround is in place for JRUBY-5642 that should be applied only to JRuby 9.2.6.0, but found 9.2.3.0
  <main> at /usr/share/logstash/lib/systeminstall/pleasewrap.rb:19
Unable to install system startup script for Logstash.
root@buster:/vagrant#
```

Comment (colinsurprenant) [reply lib/systeminstall/pleasewrap.rb]: Ah!! perfect! 🖤

**Comment by colinsurprenant** [comment]
LGTM

**Comment by jsvd** [comment]
This was also merged to:

* c05dccd3c - (6.7) work around jruby-5642 during package installation on jdk11 (#10658) 
* 261016499 - (7.0) work around jruby-5642 during package installation on jdk11 (#10658)
* 563fa8117 - (7.x) work around jruby-5642 during package installation on jdk11 (#10658)
