### PR TITLE
fix agent silent exit upon pipelines reloading

### LINKED ISSUE #10345: silent exit on pipelines reloading
under these conditions:
- pipeline reloading disabled
- using a system pipeline like the monitoring pipeline
- very long pipeline startup time due to the pipeline configuration complexity 

logstash may silently exit when issued a SIGHUP to signal pipelines reloading. 

This can be trivially reproduced by  setting the sleep to `0.1` in:
https://github.com/elastic/logstash/blob/e6d59de458b10795e18070176ca215aaecf3d68e/logstash-core/lib/logstash/agent.rb#L119-L124

And simulating a slow reload time by forcing a 5 seconds sleep on pipeline reloading in just before the `Create.new`:
https://github.com/elastic/logstash/blob/e6d59de458b10795e18070176ca215aaecf3d68e/logstash-core/lib/logstash/pipeline_action/reload.rb#L54-L56

Using any dummy pipeline configured in `pipelines.yml`, disabling pipeline reloading and enabling monitoring when issuing a SIGHUP, logstash will silently terminate.

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #10345

This PR introduces a new `PipelinesRegistry` class to encapsulate the old `Agent` `@pipelines` `ConcurrentHashMap`.  

One of the problem was the termination condition of the agent which was checking if all pipelines threads were **not** `Threah#alive?` and assumed it could exit. The problem is that the reload action did shutdown a pipeline to later on restart a new one, and in that period, all pipelines thread could have been seen as **not** `Threah#alive?`. This PR solves this condition by taking into account the reloading sequence as a period where a pipeline is not considered dead regardless if shutdown part of the reload accured or not.

### Main Changes
-  new `PipelinesRegistry` is an abstraction for the registration a management of the pipeline states which replaces the old `@pipelines` instance variable which had a getter and was directly used in other parts of the code
- correctly pass action thread parameters
- fix periodic_pollers.rb wrong parameter names
- introduce new `@finished_run`  `AtomicBoolean`
- change `@finished_execution` to **always** be true regardless of pipeline termination condition
- document semantic of both `@finished_run` and `@finished_execution`
- refactor non-autoreload agent loop 
- change `Pipeline#wait_until_started` to use `@finished_run` and document logic
- change pipeline actions to use new registry `create_pipeline`, `reload_pipeline` and `terminate_pipeline`
- change usage of `@pipelines` to use new registry collection methods

### Other Changes

- change usage of the `generator` plugin in specs with a new `dummyblockinginput`. while fixing tests these were making it almost impossible to follow the debug traces of the build because the generator inputs were outputting gigamounts of debug logs, one per emitted event. Also generator input is a waste of ressource and probably slows down the tests too. 
- made changes to make some specs more resilient to timing problems when testing the actions and agent.
- added new `HookRegistry#remove_hooks` method to the metrics input to be able to cleanup the global and static `LogStash::PLUGIN_REGISTRY` when finished - this was causing weird problems in the metrics specs where the `pipeline_started` action was being fires on unused instances of the plugin when instantiated multiple times in the specs.
- refactored `x-pack/spec/monitoring/inputs/metrics_spec.rb` to be more resilient to timing related errors (specs were always passing locally but not on slower Jenkins execution).

### CODE REVIEW

**Comment by colinsurprenant** [comment]
@yaauie thanks for the early feedback, all good, will definitely followup. For now I am still at the stage of making that work *correctly* and making sure all tests are passing, then I will definitely proceed to refactor some of this per your suggestions.

File: logstash-core/lib/logstash/pipelines_registry.rb [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+    end
+
+    def create_pipeline(pipeline_id, pipeline, &create_block)
+      success = false
+
+      @states.compute(pipeline_id) do |_, state|
+        if state
+          state.lock.synchronize do
+            if state.terminated?
+              success = create_block.call
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: I am not sure if JRuby has the same behaviour, it'd be interesting to measure. In this case this is nowhere near a critical path so performance is not a concern here - the reason I like this way of handling blocks is because the block parameter is explicit and helps better understand the intent of the method.

File: logstash-core/lib/logstash/pipelines_registry.rb [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+              state.set_terminated(!success)
+            else
+              logger.error("Attempted to create a pipeline that already exists", :pipeline_id => pipeline_id)
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: This is the case where you are trying to create a new pipeline with an id that is already in the registry but the pipeline itself it not in a terminated state so we refuse to create it.

File: logstash-core/lib/logstash/pipelines_registry.rb [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+
+    def size
+      @states.size
+    end
+
+    def empty?
+      @states.isEmpty
+    end
+
+    def running_pipelines
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: agree, I will DRY this up.

**Comment by colinsurprenant** [comment]
@yaauie 
Tests are actually green at this point - the only failure is the infamous unrelated  `WebMock::NetConnectNotAllowedError:`. 

- Note that some specs changes might seems unrelated, for example the use of `dummyblockinginput`  instead of the generator; the generator plugin actually generates gigamout of debug logs and made it super difficult to trace logs in the Jenkins console, also, using a unbounded generator when events generation is actually not required for the tests is a waste and ultimately slows tests down. 

- [ ] I will followup with some of your refactor suggestions
- [ ] I will be pushing a few minor cleanup + better comments
- [ ] A spec should be added for the new `PipelinesRegistry` class

It's up to you if you want to wait for these items to be completed to make another review pass

**Comment by colinsurprenant** [comment]
There is ONE last nasty failing test in xpack metrics and I am pretty sure its a test timing issue but can't  put my finger on the problem as I can't reproduce locally. A lots of timing-dependant/brittle tests have been fixed in this PR making these tests a lot more resilient to timing problems but this one is tenacious.

**Comment by colinsurprenant** [comment]
I am now able to reproduce x-pack test failure(s). fix incoming.

**Comment by colinsurprenant** [comment]
Green! ✅

File: logstash-core/lib/logstash/pipelines_registry.rb [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+        else
+          success = yield
+          success ? PipelineState.new(pipeline_id, pipeline) : nil
+        end
+      end
+
+      success
+    end
+
+    def terminate_pipeline(pipeline_id, &stop_block)
```
Comment (yaauie) [inline logstash-core/lib/logstash/pipelines_registry.rb]: It would be helpful to either converge on a single yield argument/return-value pattern for these three methods, or to at least document what [is yielded](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#yieldparam), what [the block should return](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#yieldreturn), and what the effect of certain return values is (if any).

As of this writing:
 - `create_pipeline` yields to the supplied block with no arguments, and expects the block to return boolean value indicating success
 - `terminate_pipeline` yields a `Pipeline` to the block, and ignores the block's return value
 - `reload_pipeline` yields the a `PipelineState`, expecting the block to return a two-tuple with a boolean value indicating success and a `Pipeline`.

File: logstash-core/lib/logstash/state_resolver.rb [hunk 5]
```diff
@@ -25,12 +25,12 @@ def resolve(pipelines, pipeline_configs)
...
       end
 
-      running_pipelines = pipeline_configs.collect(&:pipeline_id)
+      configured_pipelines = pipeline_configs.collect(&:pipeline_id)
 
       # If one of the running pipeline is not in the pipeline_configs, we assume that we need to
       # stop it.
-      pipelines.keys
-        .select { |pipeline_id| !running_pipelines.include?(pipeline_id) }
+      pipelines_registry.running_pipelines.keys
```
Comment (yaauie) [inline logstash-core/lib/logstash/state_resolver.rb]: I _think_ that your changes make better sense than the previous code, which had a variable called `running_pipelines` containing pipelines that _may-or-may-not_ be running.

Your code now checks to make sure that the _configured_ pipelines are _actually_ running before adding a stop action. If this is intentional, then :+1:

File: logstash-core/lib/logstash/agent.rb [hunk 6]
```diff
@@ -310,34 +319,35 @@ def converge_state(pipeline_actions)
         # that we currently have.
         begin
           logger.debug("Executing action", :action => action)
-          action_result = action.execute(self, pipelines)
+          action_result = action.execute(self, @pipelines_registry)
```
Comment (yaauie) [inline logstash-core/lib/logstash/agent.rb]: Not introduced by your PR, but I find the behaviour of passing the entire `self` to a method along with an instance variable of same _self_ to be a bit fishy (previously this had one more small step of indirection, passing the ivar by means of an attribute accessor). It looks like these are largely done to enable the `PipelineAction` to new-up a pipeline that links back to the agent.

No action requested on this, just something to think about.

File: logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb [hunk 7]
```diff
@@ -10,13 +10,11 @@ def initialize(metric, agent, options = {})
...
-      pipelines = @agent.with_running_user_defined_pipelines {|pipelines| pipelines}
-      unless pipelines.nil?
-        pipelines.each {|_, pipeline|
-          unless pipeline.nil?
-            pipeline.collect_dlq_stats
-          end
-        }
+      pipelines = @agent.running_user_defined_pipelines
+      pipelines.each do |_, pipeline|
+        unless pipeline.nil?
```
Comment (yaauie) [inline logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb]: In what scenarios could we have a `PipelineState` that is running, but for which we have no `Pipeline`? Can we guard against this happening upstream to simplify usage?

From what I can tell in the code, this is _theoretically_ possible if the block passed to `PipelineRegistry#reload_pipeline` failed to emit a new `Pipeline` in its tuple, but that the only use of `PipelineRegistry#reload_pipeline` does not do this.

File: logstash-core/lib/logstash/pipeline_action/reload.rb [hunk 8]
```diff
@@ -49,13 +53,35 @@ def execute(agent, pipelines)
 
       logger.info("Reloading pipeline", "pipeline.id" => pipeline_id)
 
-      stop_result = Stop.new(pipeline_id).execute(agent, pipelines)
+      success = pipelines_registry.reload_pipeline(pipeline_id) do
+        # important NOT to explicitly return from block here
+        # the block must return a success boolean value
```
Comment (yaauie) [inline logstash-core/lib/logstash/pipeline_action/reload.rb]: I prefer the term "emit" to avoid confusion with the `return` keyword that when used in blocks causes a local-jump with undefined behaviour.

```suggestion
        # the block must emit a success boolean value
```

File: logstash-core/lib/logstash/pipelines_registry.rb [hunk 9]
```diff
@@ -0,0 +1,145 @@
...
+    def terminated?
+      # a reloading pipeline is never considered terminated
+      @reloading.false? && @pipeline.finished_execution?
+    end
+
+    def set_reloading(is_reloading)
+      @reloading.value = is_reloading
+    end
+
+    def set_pipeline(pipeline)
```
Comment (yaauie) [inline logstash-core/lib/logstash/pipelines_registry.rb]: guarding against setting a `nil` pipeline may simplify usage.

File: logstash-core/spec/logstash/pipeline_action/reload_spec.rb [hunk 10]
```diff
@@ -2,15 +2,16 @@
...
 describe LogStash::PipelineAction::Reload do
   let(:metric) { LogStash::Instrument::NullMetric.new(LogStash::Instrument::Collector.new) }
   let(:pipeline_id) { :main }
-  let(:new_pipeline_config) { mock_pipeline_config(pipeline_id, "input { generator { id => 'new' } } output { null {} }", { "pipeline.reloadable" => true}) }
-  let(:pipeline_config) { "input { generator {} } output { null {} }" }
+  let(:new_pipeline_config) { mock_pipeline_config(pipeline_id, "input { dummyblockinginput { id => 'new' } } output { null {} }", { "pipeline.reloadable" => true}) }
+  let(:pipeline_config) { "input { dummyblockinginput {} } output { null {} }" }
   let(:pipeline) { mock_pipeline_from_string(pipeline_config, mock_settings("pipeline.reloadable" => true)) }
-  let(:pipelines) { chm = java.util.concurrent.ConcurrentHashMap.new; chm[pipeline_id] = pipeline; chm }
+  let(:pipelines) { chm = LogStash::PipelinesRegistry.new; chm.create_pipeline(pipeline_id, pipeline) { true }; chm }
```
Comment (yaauie) [inline logstash-core/spec/logstash/pipeline_action/reload_spec.rb]: nitpick: local variable name `chm` no longer applies

File: logstash-core/lib/logstash/pipeline_action/reload.rb [hunk 11]
```diff
@@ -49,13 +53,35 @@ def execute(agent, pipelines)
...
+        # First shutdown old pipeline
+        old_pipeline.shutdown { LogStash::ShutdownWatcher.start(old_pipeline) }
+        old_pipeline.thread.join
+
+        # Then create a new pipeline
+        new_pipeline =
+          if @pipeline_config.settings.get_value("pipeline.java_execution")
+            LogStash::JavaPipeline.new(@pipeline_config, @metric, agent)
+          else
+            agent.exclusive do
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipeline_action/reload.rb]: Good idea - I'd prefer to defer that to new PR though.

File: logstash-core/lib/logstash/pipelines_registry.rb [hunk 12]
```diff
@@ -0,0 +1,145 @@
...
+      # compute() method which is atomic; calling compute() concurrently
+      # will block until the other compute finishes so no mutex is necessary
+      # for synchronizing compute calls
+      @states = java.util.concurrent.ConcurrentHashMap.new
+    end
+
+    def create_pipeline(pipeline_id, pipeline, &create_block)
+      success = false
+
+      @states.compute(pipeline_id) do |_, state|
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: Well, we're leveraging the `ConcurrentHashMap` concurrency features and in particular the `compute` method semantics which allows us to avoid using a global lock which was the original purpose of using a `ConcurrentHashMap`. In all fairness, the only place the state object is leaked outside the `PipelineRegistry` is in the `reload` method and I think we could avoid that, I'll check. Other then that I think it is relatively straight forward. I'll go ahead and see if we can avoir leaking the state object and will also add comments to explain the logic. I did add a comment in  `PipelineRegistry#initialize` method about the `compute` method usage.

File: logstash-core/lib/logstash/pipelines_registry.rb (hunk 4 above)
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: Yes, I agree, but on the other hand, this is not really a *reusable* API, these methods we're crafter for the specific need they serve in the context of the actions. I will add documentation per your suggestion, good idea.

File: logstash-core/lib/logstash/agent.rb (hunk 6 above)
Comment (colinsurprenant) [reply logstash-core/lib/logstash/agent.rb]: totally agreed. IMO the problem here is passing the who agent object into the action which is now used for 2 purposes I believe: 1- do the `agent.exclusive` on pipeline initialization, which we could get rid with your suggestion above and 2- the use of `ExecutionContextFactory` in the pipeline. 
I think we could refactor both to get rid of the requirement of passing the whole agent. I'd like to defer that to another PR.

File: logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb (hunk 7 above)
Comment (colinsurprenant) [reply logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb]: good point, I refactored this code by essentially swapping the `with_running_user_defined_pipelines ` with `running_user_defined_pipelines` without really analyzing the original behaviour; this check is actually not necessary and we should never have a `nil` pipeline, not event from reload. From a defensive POV I am a little hesitant to remove that check to avoid unseen corner cases - I suggest to add this as a followup refactor PR to make sure there are no corner cases.

**Comment by colinsurprenant** [comment]
Thanks a lot @yaauie for the review pass - all really good comments, will submit discussed changes and create a followup issue for what I think we could defer to new  PR(s). Let me know if you are good with that.

File: logstash-core/lib/logstash/pipelines_registry.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: let me know if this makes sense

File: logstash-core/lib/logstash/pipelines_registry.rb (hunk 4 above)
Comment (colinsurprenant) [reply logstash-core/lib/logstash/pipelines_registry.rb]: BTW I am not a super fan of this block passing strategy here, I chose that manly to minimize changes in the actual pipeline actions. I think I'd prefer to keep it that way for now but will add a note to see if we could clean that up which would probably include also refactoring the actions themselves.

**Comment by yaauie** [comment]
I'm okay with all of the above-mentioned deferrals for other PRs for cleanup, and think that this PR is a good balance between solving the problem at-hand and not going too far into the weeds.

You had one outstanding comment about trying to eliminate leaking the state, and I trust you to either resolve or defer that.

:+1:

**Comment by colinsurprenant** [comment]
This time I am pretty sure I nailed the metrics specs timing issues for good 🤞

**Comment by colinsurprenant** [comment]
@yaauie 

I will not followup on these remaining tasks for now:
- Verify if we should remove states upon pipeline stop to avoid memory leaks
- Verify if we should make the PipelineState object immutable
It's ok like this for now and the potential danger for a memory leak is very remote; someone would have to keep on changing pipeline names continuously for this to become a potential problem I believe. I will also create a followup issue for this.

Also, I tried writing a spec to «assess all Agent#execute exit conditions» but was not successful. The conditions to make that happen are super hard to reproduce in specs and the testing for non-exit or for exit of `Agent#execute` is also challenging. For now I will rely on the manual tests I did where the fix actually solves the manual reproduction scenario. Also, I checked and the `Agent` specs are fairly extensive so I am confident we are ok for that.

So at this point I would be ready to move forward with the PR + creating the discussed followup issues.

**Comment by colinsurprenant** [comment]
A complementary note about not removing the states upon pipeline termination: the only impact at this point is that the `Agent#non_running_pipelines` will contain all pipelines that were terminated and never reloaded. The only condition where this will happen is when running multiple pipelines and removing or changing the name of a pipeline and issuing a reload which will terminate the delete/removed/old name pipeline definition.

The only **visible** user-facing impact will be in this **INFO** log line 
```
    logger.info(
        "Pipelines running",
        :count => running_pipelines.size,
        :running_pipelines => running_pipelines.keys,
        :non_running_pipelines => non_running_pipelines.keys
    ) if converge_result.success? && converge_result.total > 0
```
where these non running pipelines will be reported. Personally I think this is actually valuable information and the change is non-functionnal since its only a INFO log line change and will not break BWC. 

Maybe @jsvd you may want to chime in on this?

**Comment by colinsurprenant** [comment]
Thanks @yaauie for the review.
Will be creating followup issues, rebasing and merging shortly. Also it cleanly backports down to 6.5 so I suggest we do that.

**Comment by colinsurprenant** [comment]
Unrelated `WebMock::NetConnectNotAllowedError:` test failure as reported in https://github.com/elastic/logstash/issues/10274

**Comment by colinsurprenant** [comment]
jenkins test this

File: logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb (hunk 7 above)
Comment (colinsurprenant) [reply logstash-core/lib/logstash/instrument/periodic_poller/dlq.rb]: for reference; added followup issue #10405
