### PR TITLE
Explicitate the type of log format in appender's names else it breaks…

### LINKED ISSUE #12921: Log4j don't rollover nor delete files after the introduction of log per pipeline
**Logstash information**:

Please include the following information:

1. Logstash version: >= `7.5.0`
2. Logstash installation source: tar/deb
3. How is Logstash being run: command line

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
2. JVM installation source: sdkman!
3. Value of the `JAVA_HOME` environment variable if set. `/home/andrea/.sdkman/candidates/java/current`

**OS version** (`uname -a` if on a Unix-like system):
```
Linux kalispera 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
When logstash-plain.log file reached the size configured in log4j2.properties the file has to rollover, and when the rolling file appender contains a strategy that defines an action (for example delete all file older that 1 minute) it has to execute the action.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.configure pipeline with
```
input {
  java_generator {
    lines => [
      "line 1",
      "line 2",
      "line 3"
    ]
    eps => 1
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```
 2. change log4 configuration to rollover at 1Kb, no time related triggering policy and a strategy to require deletion of log files older than 1 minute (`config/log4j2.properties`):
 ```
appender.rolling.type = RollingFile
appender.rolling.name = plain_rolling
appender.rolling.fileName = ${sys:ls.logs}/logstash-${sys:ls.log.format}.log
appender.rolling.filePattern = ${sys:ls.logs}/logstash-${sys:ls.log.format}-%d{yyyy-MM-dd}-%i.log.gz
appender.rolling.policies.type = Policies
#appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
#appender.rolling.policies.time.interval = 1
#appender.rolling.policies.time.modulate = true
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = [%d{ISO8601}][%-5p][%-25c]%notEmpty{[%X{pipeline.id}]} %m%n
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 1KB
####
appender.rolling.strategy.delete.type = Delete
appender.rolling.strategy.delete.basePath = logs/
appender.rolling.strategy.delete.maxDepth = 1
appender.rolling.strategy.delete.ifLastModified.type = IfLastModified
appender.rolling.strategy.delete.ifLastModified.age = 1M
####
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 30
```
 3. run logstash in debug to produce some log traffic `bin/logstash -f pipeline.conf  --debug` and verify in`logs/`  folder that the `logstash-plain.log` becomes bigger than 1Kb and never rollover nor the rolled over files are deleted after 1 minute

**Provide logs (if relevant)**:
- `logs/` content with version `7.4.2`
```
andrea@kalispera logs $ date
Fri 21 May 2021 09:45:33 AM CEST
andrea@kalispera logs $ ls -lart
total 28
drwxr-xr-x 13 andrea andrea 4096 May 21 09:45 ..
-rw-r--r--  1 andrea andrea  251 May 21 09:45 logstash-plain-2021-05-21-18.log.gz
-rw-r--r--  1 andrea andrea  250 May 21 09:46 logstash-plain-2021-05-21-19.log.gz
-rw-r--r--  1 andrea andrea  246 May 21 09:46 logstash-plain-2021-05-21-20.log.gz
-rw-r--r--  1 andrea andrea  249 May 21 09:46 logstash-plain-2021-05-21-21.log.gz
drwxr-xr-x  2 andrea andrea 4096 May 21 09:46 .
-rw-r--r--  1 andrea andrea  768 May 21 09:46 logstash-plain.log
andrea@kalispera logs $ ls -lart
total 28
drwxr-xr-x 13 andrea andrea 4096 May 21 09:45 ..
-rw-r--r--  1 andrea andrea  246 May 21 09:46 logstash-plain-2021-05-21-20.log.gz
-rw-r--r--  1 andrea andrea  249 May 21 09:46 logstash-plain-2021-05-21-21.log.gz
-rw-r--r--  1 andrea andrea  244 May 21 09:46 logstash-plain-2021-05-21-22.log.gz
-rw-r--r--  1 andrea andrea  246 May 21 09:47 logstash-plain-2021-05-21-23.log.gz
drwxr-xr-x  2 andrea andrea 4096 May 21 09:47 .
-rw-r--r--  1 andrea andrea  225 May 21 09:47 logstash-plain.log
```

- `logs/` content with version `7.5.1`
```
andrea@kalispera logs $ ls -lart
total 32
drwxr-xr-x 13 andrea andrea  4096 May 21 09:48 ..
-rw-r--r--  1 andrea andrea     0 May 21 09:48 logstash-slowlog-plain.log
drwxr-xr-x  2 andrea andrea  4096 May 21 09:48 .
-rw-r--r--  1 andrea andrea 22590 May 21 09:48 logstash-plain.log
andrea@kalispera logs $ ls -lart
total 44
drwxr-xr-x 13 andrea andrea  4096 May 21 09:48 ..
-rw-r--r--  1 andrea andrea     0 May 21 09:48 logstash-slowlog-plain.log
drwxr-xr-x  2 andrea andrea  4096 May 21 09:48 .
-rw-r--r--  1 andrea andrea 33844 May 21 09:51 logstash-plain.log
```
the `logstash-plain.log` keeps growing.

An heavy suspect it that's related to #11108

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

Fix #12921, a bug in log4j configuration that avoid the rollover of `logstash-plain` when the flag `pipeline.separate_logs` is enabled, 

## What does this PR do?

The names of `json/plain` appenders in log4j configuration is composed using the `log.format` configuration variable, so it ends that the definition of an appender for a specific log format uses the format variable itself. 

Considering the json rolling appender:
```
appender.json_rolling.fileName = ${sys:ls.logs}/logstash-${sys:ls.log.format}.log
```
it's unseful to use `${sys:ls.log.format}` when it's defining a json appender's filename, furthermore this confuse log4j at configuration time. If we are using `plain` format this line is resolved by log4j's `StrLookup` to 
```
appender.json_rolling.fileName = logs/logstash-plain.log
```
and this is a clash with the log file used by the `appender.rolling`. For some reason this doesn't manifest any problem and the `appender.json_rolling` doesn't overwrite the plain rolling appender so the json log lines never gone into the plain log file, untill the log per pipeline feature was introduced #11108. In this case the only interference that manifests is the rollover not happening on global `logstash-plain`. The issue #12921 describe a reproducer.

## Why is it important/What is the impact to the user?

With this PR the rollover of `logstash-plain.log` works also when the log per pipeline (`pipeline.separate_logs`) is enabled.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [x] I have made corresponding change to the default configuration files (and/or docker env variables)
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [x] change the configuration in the other locations
- [x] create an integration test to verify it

## Related issues

- Relates #11108
- Fixes #12921

### CODE REVIEW

File: qa/integration/specs/pipeline_log_spec.rb [hunk 1]
```diff
@@ -112,6 +113,32 @@
...
+      "path.logs" => temp_dir,
+      "pipeline.id" => pipeline_name,
+      "pipeline.separate_logs" => true
+    }
+    FileUtils.mkdir_p(File.join(temp_dir, "data"))
+    data = File.join(temp_dir, "data")
+    settings = settings.merge({ "path.data" => data })
+    IO.write(File.join(temp_dir, "logstash.yml"), YAML.dump(settings))
+
+    FileUtils.cp("fixtures/logs_rollover/log4j2.properties", temp_dir)
```
Comment (kares) [inline qa/integration/specs/pipeline_log_spec.rb:128]: seems there isn't that much difference in the fixture properties file, 
would it be feasible to generate a .properties based on actual `config/log4j2.properties` here 
and add/replace lines - to make sure we stay in sync?

possible future changes to *config/log4j2.properties* might cause we end up testing a non-production config ...

**Review by kares — COMMENTED** [review]
haven't tested the setup locally but the passing integration spec gives me confidence that this indeed does what it is supposed to - one slight glitch is that we do not test the "actual" *config/log4j2.properties* configuration (wdyt would that be possible?)

File: qa/integration/specs/pipeline_log_spec.rb [hunk 2]
```diff
@@ -133,11 +160,11 @@
   end
 
   @private
```
Comment (yaauie) [inline qa/integration/specs/pipeline_log_spec.rb:162]: unrelated, but worth cleaning up.

It looks like this is meant to use `Module#private`, which causes subsequent `def`'s in the current scope to be defined privately. As-is, it simply references the `@private` ivar and ignores the result.

Since this is in an rspec example group, we don't really have the _concept_ of public and private methods; methods defined using `def` are only available to examples within the group, so they are _effectively_-private without any further action.

```suggestion
```

**Review by yaauie — APPROVED** [review]
LGTM. I agree with your analysis -- good find.

I've left one semi-unrelated suggestion -- it's a no-op cleanup.

I agree somewhat with @kares that there is risk of production config drifting from these fixtures. From what I can see, the only real way to eliminate drift is for Logstash to "own" the interface for log configuration instead of making our users muck with log4j configs (or even _allowing_ them to do so). Unfortunately, that would require a significant investment that I don't see bubbling up to the top of the priority list in the near future.

In that sense, I think that the risk of divergence is a necessity that can't be easily avoided.

File: qa/integration/specs/pipeline_log_spec.rb (hunk 1 above)
Comment (andsel) [reply qa/integration/specs/pipeline_log_spec.rb:128]: Good point, I think we could have a good compromise with a Gradle task that copies the production `łog4j2.properties` and test against that

Comment (andsel) [reply qa/integration/specs/pipeline_log_spec.rb:128]: after it had changed the size of the rollover part

**Comment by andsel** [comment]
@kares I've added a task to copy the production log4j config and modify it in a couple of lines to make it runnable inside the integration tests. Would be great if you can give it an eye, the red CI is due to something unrelated to this PR

**Review by kares — COMMENTED** [review]
looking good - would appreciate having a check that we'll end up with a 1KB rollover configuration in the integration test, if it's not too much trouble...

File: qa/integration/build.gradle [hunk 3]
```diff
@@ -39,7 +39,30 @@ test {
...
+
+tasks.register("copyProductionLog4jConfiguration", Copy) {
+  description "Copy the production log4j config to be tested in QA (qa/integration/fixtures/logs_rollover)"
+
+  from "${projectDir}/../../config/log4j2.properties"
+  into "${projectDir}/fixtures/logs_rollover/"
+  filter {
+    // modify rollover policy to make it happen in integration test without need to generate tons of log lines
+    line -> line
+            .replace('appender.rolling.policies.size.size = 100MB',
```
[the remark this answers is not in the document]
Comment (andsel) [reply qa/integration/build.gradle:50]: Hi @kares thanks for hint, the pre-test checks are now presents in the integration spec. It's ready for your eyes :-)

**Review by kares — APPROVED** [review]
:ice_cream:
