### PR TITLE
Pipeline to pipeline communication acked queue improvements.

### LINKED ISSUE #15159: Pipeline terminated after `Tried to write to a closed queue.` error.
**Logstash information**:

Please include the following information:

1. Logstash version: `8.4.1` and above (`8.8.2`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker): clone the Logstash repo and run from source or run `8.4.1`
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): command line `./bin/logstash`

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`): `openjdk 17.0.4.1 2022-08-12 LTS`
**OS version** (`uname -a` if on a Unix-like system): `Darwin mashhurs.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64`

**Description of the problem including expected versus actual behavior**:
Current behavior is upstream pipeline gets terminated. Expected behavior, the upstream pipeline shouldn't get terminated.

**Steps to reproduce**:

Use Central Pipeline Management and deploy pipelines.

 1. create `upstream` and `downstream` pipelines, config provided below with screenshots. Also do not forget to enable PQ (`queue.type: persisted`) in `logstash.yml` and decrease PQ page capacity (`queue.page_capacity: 512kb`) to easier reproducing;
 2. use `ruby-filter` in downstream pipeline to make slower output-throughput, using either `raise` exception or `sleep`
 3. after sometime, remove `ruby-filter` (or just add a code which doesn't blocks pipeline, `puts 'Hi!'` example) and deploy
 4. you will see the error

- `upstream` pipeline view in CPM:
image

- `downstream` pipeline view in CPM:
image

**Provide logs (if relevant)**:
```

[2023-07-09T09:52:24,717][INFO ][logstash.javapipeline    ][downstream] Pipeline terminated {"pipeline.id"=>"downstream"}
[2023-07-09T09:52:24,720][ERROR][logstash.javapipeline    ][upstream] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"upstream", :error=>"Tried to write to a closed queue.", :exception=>Java::JavaLang::IllegalStateException, :backtrace=>["org.logstash.ext.JrubyAckedWriteClientExt.ensureOpen(org/logstash/ext/JrubyAckedWriteClientExt.java:94)", "org.logstash.ext.JrubyAckedWriteClientExt.doPush(org/logstash/ext/JrubyAckedWriteClientExt.java:77)", "org.logstash.ext.JRubyWrappedWriteClientExt.push(org/logstash/ext/JRubyWrappedWriteClientExt.java:102)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.plugins.builtin.pipeline.input.internalReceive(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash/plugins/builtin/pipeline//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:67)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:309)", "org.jruby.javasupport.Java$ProcToInterface.callProc(org/jruby/javasupport/Java.java:1237)", "org.jruby.javasupport.Java$ProcToInterface.access$300(org/jruby/javasupport/Java.java:1214)", "org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(org/jruby/javasupport/Java.java:1275)", "java.util.stream.ForEachOps$ForEachOp$OfRef.accept(java/util/stream/ForEachOps.java:183)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:197)", "java.util.Spliterators$ArraySpliterator.forEachRemaining(java/util/Spliterators.java:992)", "java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:509)", "java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:499)", "java.util.stream.ForEachOps$ForEachOp.evaluateSequential(java/util/stream/ForEachOps.java:150)", "java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(java/util/stream/ForEachOps.java:173)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline.forEach(java/util/stream/ReferencePipeline.java:596)", "jdk.internal.reflect.GeneratedMethodAccessor25.invoke(jdk/internal/reflect/GeneratedMethodAccessor25)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:457)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:318)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.plugins.builtin.pipeline.input.internalReceive(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash/plugins/builtin/pipeline//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:65)", "org.logstash.plugins.pipeline.PipelineBus.lambda$sendEvents$1(org/logstash/plugins/pipeline/PipelineBus.java:76)", "java.util.concurrent.ConcurrentHashMap.forEach(java/util/concurrent/ConcurrentHashMap.java:1603)", "org.logstash.plugins.pipeline.PipelineBus.sendEvents(org/logstash/plugins/pipeline/PipelineBus.java:64)", "jdk.internal.reflect.GeneratedMethodAccessor24.invoke(jdk/internal/reflect/GeneratedMethodAccessor24)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:487)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:342)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.plugins.builtin.pipeline.output.multi_receive(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash/plugins/builtin/pipeline//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/output.rb:39)", "org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.invokeOutput(org/logstash/config/ir/compiler/OutputStrategyExt.java:153)", "org.logstash.config.ir.compiler.OutputStrategyExt$SimpleAbstractOutputStrategyExt.doOutput(org/logstash/config/ir/compiler/OutputStrategyExt.java:279)", "org.logstash.config.ir.compiler.OutputStrategyExt$SharedOutputStrategyExt.output(org/logstash/config/ir/compiler/OutputStrategyExt.java:312)", "org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multiReceive(org/logstash/config/ir/compiler/OutputStrategyExt.java:143)", "org.logstash.config.ir.compiler.OutputDelegatorExt.doOutput(org/logstash/config/ir/compiler/OutputDelegatorExt.java:102)", "org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121)", "org.logstash.generated.CompiledDataset1.compute(org/logstash/generated/CompiledDataset1)", "org.logstash.config.ir.CompiledPipeline$CompiledOrderedExecution.compute(org/logstash/config/ir/CompiledPipeline.java:319)", "org.logstash.config.ir.CompiledPipeline$CompiledOrderedExecution.compute(org/logstash/config/ir/CompiledPipeline.java:306)", "org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:87)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:77)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:427)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:294)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:300)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:309)", "java.lang.Thread.run(java/lang/Thread.java:833)"], :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 sleep>"}
[2023-07-09T09:52:24,729][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:25,331][INFO ][logstash.javapipeline    ] Pipeline `downstream` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2023-07-09T09:52:25,333][WARN ][logstash.javapipeline    ][downstream] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
[2023-07-09T09:52:25,337][INFO ][logstash.javapipeline    ][downstream] Starting pipeline {:pipeline_id=>"downstream", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x79270825 run>"}
[2023-07-09T09:52:25,347][INFO ][logstash.javapipeline    ][downstream] Pipeline Java execution initialization time {"seconds"=>0.01}

[2023-07-09T09:52:25,735][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:26,741][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:27,748][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:28,754][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:29,758][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:30,763][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:31,770][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:32,773][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:33,778][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:34,806][ERROR][logstash.javapipeline    ][upstream] Pipeline error {:pipeline_id=>"upstream", :exception=>#<RuntimeError: Unable to stop input plugin(s)>, :backtrace=>["/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:370:in `block in monitor_inputs_and_workers'", "org/jruby/RubyKernel.java:1507:in `loop'", "/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:341:in `monitor_inputs_and_workers'", "/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `run'", "/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:142:in `block in start'"], "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:34,807][INFO ][logstash.javapipeline    ][upstream] Pipeline terminated {"pipeline.id"=>"upstream"}
```

### PR DESCRIPTION
**Pull request by mashhurs**
## Release notes

Resolves upstream pipeline termination when using pipeline to pipeline communication if writing to a closed queue.

## What does this PR do?
Adresses number of Pipeline to Pipeline upstream issues including abnormal termination issues:
  - `"Tried to write to a closed queue." IllegalStateException` exception, terminates upstream pipeline
    Resolution: ideally locking `input` in the pipeline bus while sending the inflight event would be a synchronized task to prevent such cases and we have [this option](https://gist.github.com/yaauie/5bf4db9f7f7bd17d6b0b84741940a9a1) (big thanks @yaauie) to consider. However, blocking mechanism would be an expensive and expected behavior is to catch exception (failed inflight send position) and let process retry as we have a logic in pipeline bus.

  - Inflight events duplicate while sending
    Issue: when sending inflight events to terminated downstream pipeline, we retry from the failed position we lastly sent. However, we have a bug that we copy the events to send from the point where cloned event's failed position.
    Resolution: the failed position should be a cumulative number, should correspond origin event's position as `lastFailedPosition += lastResponse.getSequencePosition();`

  - `"Cannot invoke "org.logstash.ackedqueue.Page.hasCapacity(int)" because "this.headPage" is null"`
      `NullPointerException` exception. It happens when `ensure_delivery => true`, the situation where queue is closed but input is trying to write into it.
    (reproduce with 3 upstream pipeline workers, single downstream pipeline with 1000 batch)
    Resolution: use atomic `Queue->isClosed()` and check for null to prevent headPage NPE
    Note: when `ensure_delivery => false`, pipeline ignores failed inflight events, means it doesn't write to queue.

  - Queue closed check improvements
    `JRubyWrappedAckedQueueExt` implemented its own `isClosed` atomic variable to identify if queue is closed. However, since `input` is a volatile in pipeline bus (even if not), aligned on actual `closed` variable of original `Queue` is an accurate.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally
- See https://github.com/elastic/logstash/issues/15159 how to test `Tried to write to a closed queue.` the issue.
- Inflight events lost issue is hard to test.
- `Cannot invoke "org.logstash.ackedqueue.Page.hasCapacity(int)" because "this.headPage" is null` NPE test also hard. There is 1% percent of possibility to make it happen when using multiple upstream workers and single downstream worker with small (ex: up to 100) batch size.

## Related issues

- Closes #15159 

## Use cases

Please see the description for the use-case and details of resolution

## Logs after change, see issue description for before change logs.
```
[2023-08-02T11:51:29,367][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:downstream}
[2023-08-02T11:51:33,814][INFO ][logstash.javapipeline    ][downstream] Pipeline terminated {"pipeline.id"=>"downstream"}
[2023-08-02T11:51:33,815][WARN ][org.logstash.plugins.pipeline.PipelineBus][upstream][c28fc23a0d8a4f050c8fd52237d2d161521029e2ebd918ed033ba8725cb5886a] Attempted to send events to 'myDownstreamPipeline' but that address reached error condition with 35 events remaining. Will Retry. Root cause Tried to write to a closed queue.
[2023-08-02T11:51:34,448][INFO ][logstash.javapipeline    ] Pipeline `downstream` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2023-08-02T11:51:34,450][WARN ][logstash.javapipeline    ][downstream] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
[2023-08-02T11:51:34,451][INFO ][logstash.javapipeline    ][downstream] Starting pipeline {:pipeline_id=>"downstream", "pipeline.workers"=>1, "pipeline.batch.size"=>100, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>100, "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x2e3fbf20 /Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:134 run>"}
[2023-08-02T11:51:34,459][INFO ][logstash.javapipeline    ][downstream] Pipeline Java execution initialization time {"seconds"=>0.01}
[2023-08-02T11:51:34,460][INFO ][logstash.javapipeline    ][downstream] Pipeline started {"pipeline.id"=>"downstream"}
[2023-08-02T11:51:34,466][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:downstream, :upstream], :non_running_pipelines=>[]}
```

### CODE REVIEW

File: logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb [hunk 1]
```diff
@@ -68,9 +68,11 @@ def internalReceive(events)
         stream_position = stream_position + 1
       end)
       ReceiveResponse.completed()
-    rescue java.lang.InterruptedException, IOError => e
-      # maybe an IOException in enqueueing
-      logger.debug? && logger.debug('queueing event failed', message: e.message, exception: e.class, backtrace: e.backtrace)
+    rescue org.logstash.ackedqueue.QueueRuntimeException, java.io.IOException, IOError => e
```
Comment (mashhurs) [inline logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:71]: review note: some of Java `IOException`s converted to Ruby `IOError` but majority of (`Queue` and `Page` objects) `IOException`s directly come here.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 2]
```diff
@@ -849,7 +855,7 @@ public long getUnackedCount() {
         }
     }
 
-    private boolean isClosed() {
+    public boolean isClosed() {
```
Comment (mashhurs) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:858]: review note: exposed to wrapper client to access `isClosed` rather than wrapper client duplicates and manages its own close feature.

File: logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java [hunk 3]
```diff
@@ -48,7 +51,6 @@ public final class JRubyWrappedAckedQueueExt extends AbstractWrappedQueueExt {
     private static final long serialVersionUID = 1L;
 
     private JRubyAckedQueueExt queue;
-    private final AtomicBoolean isClosed = new AtomicBoolean();
```
Comment (mashhurs) [inline logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java:51]: review note: for better atomicy/consistency, exposed `Queue->isClosed()` and used instead. This is a duplicate of `Queue#closed`, hidden bug that we are allowing to write to queue even after `Queue#closed` `true` but `isClosed` is still `false`.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 4]
```diff
@@ -413,12 +415,16 @@ public long write(Queueable element) throws IOException {
 
         lock.lock();
         try {
-            if (! this.headPage.hasCapacity(data.length)) {
-                throw new IOException("data to be written is bigger than page capacity");
+            if (this.closed.get()) {
```
Comment (mashhurs) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:418]: review note: without this condition we occasionally get `this.headPage`

File: logstash-core/src/main/java/org/logstash/ackedqueue/QueueExceptionMessages.java [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+ * under the License.
+ */
+
+
+package org.logstash.ackedqueue;
+
+/**
+ * A public class holds number of descriptive messages are used during the interaction with acked queue.
+ */
+public class QueueExceptionMessages {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ackedqueue/QueueExceptionMessages.java:26]: Nit: I think these can safely belong with `QueueRuntimeException.java`.

Out-of-scope future-refactor note: it would be nice if `QueueRuntimeException` were abstract, and had a concrete implementation for each exception type that included its own message. This would encourage the throwing of a `QueueRuntimeException` toward type-safety and allow code that needs to handle `QueueRuntimeException` to safely handle specific things.

File: logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java [hunk 6]
```diff
@@ -81,10 +81,11 @@ public void sendEvents(final PipelineOutput sender,
                         if (lastResponse != null && lastResponse.getStatus() == PipelineInput.ReceiveStatus.FAIL) {
                             // when last call to internalReceive generated a fail, restart from the
                             // fail position to avoid reprocessing of some events in the downstream.
-                            lastFailedPosition = lastResponse.getSequencePosition();
+                            // we get 0~clones.length position on failure, keep tracking failed position to correctly copy from original orderedEvents
+                            lastFailedPosition += lastResponse.getSequencePosition();
 
                             logger.warn("Attempted to send event to '{}' but that address reached error condition. " +
-                                    "Will Retry. Root cause {}", address, lastResponse.getCauseMessage());
+                                    "Will Retry. Root cause {} Failed at {} position.", address, lastResponse.getCauseMessage(), lastFailedPosition);
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java:88]: 🤔 I think this message in general is a little misleading, and want to avoid making it more so. The failure occurred while sending a _batch_ of events to the output, and the `lastFailedPosition` is _really_ the marker for the last known _success_.

Maybe something like this indicating how many events are remaining?

~~~ java
                            logger.warn("Attempted to send events to '{}' but that address reached error condition with {} events remaining. " +
                                    "Will Retry. Root cause {}", address, orderedEvents.length - lastFailedPosition, lastResponse.getCauseMessage());
~~~

File: logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java [hunk 7]
```diff
@@ -78,18 +80,18 @@ public JRubyAckedQueueExt rubyGetQueue() {
...
     @JRubyMethod(name = {"push", "<<"})
     public void rubyPush(ThreadContext context, IRubyObject event) {
-        checkIfClosed("write");
         queue.rubyWrite(context, ((JrubyEventExtLibrary.RubyEvent) event).getEvent());
     }
 
     @JRubyMethod(name = "read_batch")
     public IRubyObject rubyReadBatch(ThreadContext context, IRubyObject size, IRubyObject wait) {
-        checkIfClosed("read a batch");
+        if (queue.isClosed()) {
```
[the remark this answers is not in the document]
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ackedqueue/ext/JRubyWrappedAckedQueueExt.java]: `Queue#readBatch` is a magic method, it is `synchronized`, also reentrantly locked which I have a _concern_ about moving closed check into `Queue#readBatch`.
The `JRubyWrappedAckedQueueExt` was emulating `isClosed` by synchronizing its atomic `closed` with `Queue#closed`. With current change, we decrease a risk of synchronization delay, especially since our `input` is `volatile`. As a small improvement with recent commit, moved closed check right before `Queue@readBatch` call in `JRubyAckedQueueExt#readBatch`.

File: logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java [hunk 8]
```diff
@@ -1145,4 +1145,19 @@ public void firstUnackedPagePointToFullyAckedPurgedPage() throws Exception {
...
+        try {
+            Queue queue = new Queue(settings);
+            queue.open();
+            queue.write(new StringElement("First test string to be written in queue."));
+            queue.write(new StringElement("Second test string to be written in queue."));
+            queue.close();
+            queue.write(new StringElement("Third test string to be REJECTED to write in queue."));
+        } catch (QueueRuntimeException e) {
+            assertThat(e.getMessage(), CoreMatchers.containsString("Tried to write to a closed queue."));
+        }
```
Comment (yaauie) [inline logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java:1161]: As-written, this test does not actually assert that an exception is thrown, only that _if_ it is thrown its message matches the desired pattern.

Additionally, any failure we encounter during the setup operations would be indistinguishable from a failure of the behaviour we are attempting to specify.

Normally, I like using JUnit's `Assert.assertThrows()` to assert for a specific block, which would look like this:

```suggestion
        Settings settings = TestSettings.persistedQueueSettings(100, dataPath);
        Queue queue = new Queue(settings);

        queue.open();
        queue.write(new StringElement("First test string to be written in queue."));
        queue.write(new StringElement("Second test string to be written in queue."));
        queue.close();

        final QueueRuntimeException qre = assertThrows(QueueRuntimeException.class, () -> {
            queue.write(new StringElement("Third test string to be REJECTED to write in queue."));
        });
        assertThat(qre.getMessage(), containsString("Tried to write to a closed queue."));
```

I don't think we have a recent enough JUnit activated, so a limited emulation of its behaviour is:

~~~ java

    @FunctionalInterface
    private interface Executable {
        void execute() throws Throwable;
    }

    static <T extends Throwable> T assertThrows(Class<T> expectedType, Executable executable) {
        try {
            executable.execute();
        } catch (Throwable actual) {
            Assert.assertThat(actual, Matchers.instanceOf(expectedType));
            return expectedType.cast(actual);
        }

        throw new AssertionError(String.format("Expected %s to be thrown, but nothing was thrown.", expectedType.getName()));
    }
~~~

File: logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java [hunk 9]
```diff
@@ -43,29 +46,37 @@ public JrubyMemoryWriteClientExt(final Ruby runtime, final RubyClass metaClass)
...
+            final BlockingQueue<JrubyEventExtLibrary.RubyEvent> queue) {
         return new JrubyMemoryWriteClientExt(RubyUtil.RUBY,
-            RubyUtil.MEMORY_WRITE_CLIENT_CLASS, queue);
+                RubyUtil.MEMORY_WRITE_CLIENT_CLASS, queue);
     }
 
     @Override
     protected JRubyAbstractQueueWriteClientExt doPush(final ThreadContext context,
-        final JrubyEventExtLibrary.RubyEvent event)
-        throws InterruptedException {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java:60]: Pulling the `throws InterrutedException` off of `JRubyAbstractQueueWriteClientExt#doPush` (and similar methods) greatly expands the scope of possible effect. I am _very_ hesitant to recast interruptions as runtime issues, as interruptions are most often caused by a shutdown in progress and determining the net effect could be a monumental effort. A quick look at the underlying queue implementation for the memory queue indicates that the close operation is a no-op and theoretically _shouldn't_ result in interruptions, but I haven't also validated the pipeline shutdown path to see if stalled threads can also be interrupted from the outside.

**Review by yaauie — COMMENTED** [review]
In general, this looks to be closing in on the issue.

I would strongly prefer to make throwing `QueueRuntimeException` an _additive_ change to the queue clients, and to avoid attempting to re-map the existing `InterruptedException` that is a part of the queue clients until a separate effort where we can properly analyze the scope of effect.

File: logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java (hunk 9 above)
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ext/JrubyMemoryWriteClientExt.java:60]: I have pulled off of introducing `QueueRuntimeException` exception on queue operations, including wrapping `InterruptedException`s. The reason, I am not 100% confident if clients/callers (especially ruby plugin sources) properly handling the exceptions, especially if they intentionally expect the `InterruptedException`.

Stepping back to origin `"Tried to write to a closed queue." IllegalStateException` issue, replacing `IllegalStateException` with `QueueRuntimeException` in specific locations such as `JrubyAckedWriteClient#push()`, `Queue#constructor()` or raising it when queue closed seems to me a meaningful change.

File: logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java [hunk 10]
```diff
@@ -41,66 +43,51 @@ public final class JrubyAckedWriteClientExt extends JRubyAbstractQueueWriteClien
...
-        }
-    }
-
     @Override
     public void push(Map<String, Object> event) {
         try {
             queue.write(new Event(event));
         } catch (IOException e) {
-            throw new IllegalStateException(e);
+            throw new QueueRuntimeException(QueueExceptionMessages.WRITE_TO_CLOSED_QUEUE, e);
```
[the remark this answers is not in the document]
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java:90]: Yeah agree. More than that, my main concern was, except the `IOException`, we could get various exception types. For example:
- `Page#write()->write() -> IllegalStateException` (`this.headPage`)
- `Condition.signal() -> IllegalMonitorStateException` (`notEmpty`)

This is why I have wrapped exception to be catchable in the pipeline bus. One thing I am seeing as an improvement, I could give a better descriptive message instead of closed queue, say `exception while writing to a queue` and original _any_ type of exception wrapped by `QueueRuntimeException(QueueExceptionMessages.WRITE_TO_CLOSED_QUEUE, e)` would provide extra details.

Any better option are you seeing here?

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 11]
```diff
@@ -100,8 +101,9 @@ public Queue(Settings settings) {
             }
             this.dirPath = queueDir.toRealPath();
         } catch (final IOException ex) {
-            throw new IllegalStateException(ex);
+            throw new QueueRuntimeException(QueueExceptionMessages.CREATING_QUEUE_DIR_ERROR, ex);
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:104]: this should still be an `IllegalStateException`. It is not a runtime error and indicates that the queue could not be created due to an unexpected illegal state.

File: logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb [hunk 12]
```diff
@@ -68,9 +68,11 @@ def internalReceive(events)
...
       end)
       ReceiveResponse.completed()
-    rescue java.lang.InterruptedException, IOError => e
-      # maybe an IOException in enqueueing
-      logger.debug? && logger.debug('queueing event failed', message: e.message, exception: e.class, backtrace: e.backtrace)
+    rescue java.lang.InterruptedException, org.logstash.ackedqueue.QueueRuntimeException, java.io.IOException, IOError => e
+      # maybe an IOException in enqueueing, majority of IOExceptions are not wrapped with Ruby IOError
+      # WARN is intentional, if ensure_delivery disabled we lose warnings in PipelineBus.java caused by ReceiveResponse.failed_at(stream_position, e)
+      logger.warn('queueing event failed', message: e.message, exception: e.class)
+      logger.debug? && logger.debug('queueing event failed trace', message: e.message, exception: e.class, backtrace: e.backtrace)
```
Comment (yaauie) [inline logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:75]: A couple things here:

1) `@queue << event` routes through `JrubyAbstractQueueWriteClient#rubyPush`, which in turn routes to `JRubyAbstractQueueWriteClient#doPush`, whose PQ implementation routes through `JRubyAckedQueueExt#rubyWrite` which catches all `java.io.IOException` and re-casts them as ruby `IOError`s (and whose MQ implementation doesn't throw `IOException` at all). Therefore we don't need to add `java.io.IOException` to the rescue clause.
2) The pipeline bus is capable of logging for itself, including making decisions based on the value of its `ensureDelivery`. I would recommend _keeping_ this log message at debug-level and _adding_ warn-on-drop message to the pipeline bus.

File: logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java]: 🤦 Yeah agreed, it doesn't make sense to retry the process (through `input.rb`) on `IOException` cases.

File: logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb (hunk 12 above)
Comment (mashhurs) [reply logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb]: 1. Yup, confused `@queue.class` when changing and we do have a single entry which throws `IOError`, removed `java.io.IOException`.
This might be out of scope now but I think retrying sending process on `IOError` also doesn't make sense to me. Consequently failure point relates to IO operation which are unhandleable in an application level.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 13]
```diff
@@ -792,8 +807,13 @@ private void releaseLockAndSwallow() {
...
      * @return {@link Page} will be either a read-only tail page or the head page.
+     * @throws QueueRuntimeException if queue is closed
      */
     public Page nextReadPage() {
+        if (isClosed()) {
+            throw new QueueRuntimeException(QueueExceptionMessages.WHILE_READING_NEXT_PAGE);
+        }
+
         lock.lock();
         try {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:818]: For safety, we should do the check _after_ acquiring the lock else our check could be invalid by the time the lock has been acquired (yes, we happen to know that our `lock` of type `Lock` is a `ReentrantLock`, and the current callers of this public `nextReadPage()` method only do so after acquiring the reentrant lock, but these details aren't enough to make this public method safe on its own). 

In the write-case we _also_ check before acquiring the lock in order to "fail fast" and skip potentially-expensive serialization overhead, but here in the read-case I don't think that is necessary.

```suggestion
        lock.lock();
        try {
            if (isClosed()) {
                throw new QueueRuntimeException(QueueExceptionMessages.WHILE_READING_NEXT_PAGE);
            }

```

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 14]
```diff
@@ -599,9 +609,14 @@ public synchronized Batch nonBlockReadBatch(int limit) throws IOException {
...
+     * @throws QueueRuntimeException if queue is closed
      * @throws IOException if an IO error occurs
      */
     public synchronized Batch readBatch(int limit, long timeout) throws IOException {
+        if (isClosed()) {
+            throw new QueueRuntimeException(QueueExceptionMessages.WHILE_READING);
+        }
+
         lock.lock();
         try {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:621]: Both this `readBatch` and the companion `nonBlockReadBatch` use shared and already-guarded `nextReadPage`, so I don't think this pre-check adds value.

```suggestion
        lock.lock();
        try {
```

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java (hunk 13 above)
Comment (yaauie) [reply logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:818]: Related: I see nothing outside of `Queue` calling `Queue#nextReadPage()`, and its details are tightly-coupled with the `Queue` implementation itself. Can it be made `private`?

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 15]
```diff
@@ -599,9 +609,14 @@ public synchronized Batch nonBlockReadBatch(int limit) throws IOException {
      * @param limit size limit of the batch to read. returned {@link Batch} can be smaller.
      * @param timeout the maximum time to wait in milliseconds on write operations
      * @return the read {@link Batch} or null if no element upon timeout
+     * @throws QueueRuntimeException if queue is closed
      * @throws IOException if an IO error occurs
      */
     public synchronized Batch readBatch(int limit, long timeout) throws IOException {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:615]: Deep dive note: Both `readBatch` and `nonBlockReadBatch` were _intentionally_ made `synchronized` in https://github.com/elastic/logstash/pull/9646:

> The actual behaviour change happens by making the read methods `synchronized`. **This ensures that all elements in a batch have contiguous sequence numbers.** The reason for this is, that now only a single reader goes to sleep on the `empty` `Condition` at any given time.

**Review by yaauie — COMMENTED** [review]
We're honing in on it, just a couple more comments in this iteration.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java (hunk 13 above)
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:818]: Yeah, how do you think if we make `Queue#nextReadPage` private and place queue-close check in `Queue#readPageBatch` after acquiring lock? Making queue close-check visible in reading batch operations would be more meaningful I think.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 16]
```diff
@@ -849,7 +869,7 @@ public long getUnackedCount() {
         }
     }
 
-    private boolean isClosed() {
+    public boolean isClosed() {
```
Comment (mashhurs) [inline logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:872]: self-note: this should be private now.

File: logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb (hunk 12 above)
Comment (mashhurs) [reply logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb]: 2. We could place it in `PipelineBus.java#sendEvents()` (as shown example below) but any thread accessing this point makes noise even after volatile input becomes unavailable in the address bus. - confirmed to be sure.

```
...
    if (!ensureDelivery && !sendWasSuccess) {
        logger.warn("`ensure_delivery` is disabled in pipeline-to-pipeline communication. Some event sends failed, throwing remaining inflight {} events.", orderedEvents.length - lastFailedPosition);
    }
} while (partialProcessing);
```

image

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java (hunk 13 above)
Comment (yaauie) [reply logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:818]: This `Queue#nextReadPage` cannot reliably provide a "next read page" when the queue is closed so either it should validate that the queue is not closed or it should not be called when the queue is closed. Pushing the check down to `Queue#readPageBatch` requires sending it a `Page` that may or may not be meaningless.

`Queue#readPageBatch` _does_ check to see if the queue is closed, but the intent is different; it _assumes_ that the queue was open when it began reading, and only checks to see if the queue has _become_ closed after awaiting a fully-read head page to determine if it needs to stop trying to read and emit the already-read events.

Separately, the Queue really _should not_ return a `Page` to a thread that does not have exclusive access to it, which is what we allow by having a public method that acquires and releases the lock before returning a `Page`. This is the _only_ public method on `Queue` that exposes `Page` directly, and there is no reason for doing so.

Together, I think that:

 - `Queue#nextReadPage` should be `private` (to close abstraction-leak of `Page`, which is otherwise not a part of the public interface of `Queue`)
 - `Queue#nextReadPage` and should _assert_ that the lock is held by the current thread (with `ReentrantLock#isHeldByCurrentThread`, which would require the `Queue.lock` field type to be more specific) before calculating instead of acquire-calculate-release (to prevent the `Page` from being given to a caller that does not have exclusive access)
 - Either
   - a single queue-closed check should be done in `Queue#nextReadPage` after validating that the current thread has the lock (I favor this one because it is more DRY); or
   - a pair of queue-closed checks should be done in `Queue#readBatch` and `Queue#nonBlockReadBatch` after each acquires the lock.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java (hunk 16 above)
Comment (yaauie) [reply logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:872]: I am a little surprised that this isn't referenced from outside `Queue` (although I haven't fully-proven it, as the `JRubyAckedQueueExt#getQueue` could provide a JRuby-proxy that would map `closed?` to `isClosed()` etc).

I don't see a need to remove it from the public API; it is reasonable for a caller to inquire about this, and there is risk of missing a ruby-land call.

File: logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb [hunk 17]
```diff
@@ -68,9 +68,10 @@ def internalReceive(events)
         stream_position = stream_position + 1
       end)
       ReceiveResponse.completed()
-    rescue java.lang.InterruptedException, IOError => e
-      # maybe an IOException in enqueueing
-      logger.debug? && logger.debug('queueing event failed', message: e.message, exception: e.class, backtrace: e.backtrace)
+    rescue java.lang.InterruptedException, org.logstash.ackedqueue.QueueRuntimeException, IOError => e
+      # WARN is intentional, if ensure_delivery disabled we lose warnings in PipelineBus.java caused by ReceiveResponse.failed_at(stream_position, e)
+      logger.warn('queueing event failed', message: e.message, exception: e.class)
+      logger.debug? && logger.debug('queueing event failed trace', message: e.message, exception: e.class, backtrace: e.backtrace)
```
Comment (yaauie) [inline logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:74]: Per the semantics of `ensure_delivered => false` and its need to be explicitly-configured by the sender, I am _not_ in favor of elevating missed deliveries to `WARN`-level logs.

We know that customers rely on this feature to configure upstream pipelines to send events to downstream ones if they exist and to tolerate missing pipelines, and we do not want to flood them with warnings when they have already explicitly asked for behaviour that tolerates downstream being missing.

```suggestion
      logger.debug? && logger.debug('queueing event failed', message: e.message, exception: e.class, backtrace: e.backtrace)
```

File: logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java [hunk 18]
```diff
@@ -41,67 +40,48 @@ public final class JrubyAckedWriteClientExt extends JRubyAbstractQueueWriteClien
 
     private JRubyAckedQueueExt queue;
 
-    private AtomicBoolean closed = new AtomicBoolean();
-
     @JRubyMethod(meta = true, required = 2)
     public static JrubyAckedWriteClientExt create(final ThreadContext context, final IRubyObject recv,
```
[the remark this answers is not in the document]
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java:44]: I was very careful to make a change this Ruby method since it may _widely_ affect. However, digging a bit more shows brighter history that we had `logstash-core/lib/logstash/util/wrapped_acked_queue.rb` file before and it had [a reference for this method](https://github.com/elastic/logstash/commit/4ada6dbf4d0c2360678447a4abad80d767388d9c#diff-15bd74ca425847c432852b95f8e9e727408ddb4e019cd665fb3a52a215627508R58). It seems we migrated `wrapped_acked_queue.rb` to Java with [this change](https://github.com/elastic/logstash/pull/9111/files#diff-15bd74ca425847c432852b95f8e9e727408ddb4e019cd665fb3a52a215627508) and we no longer require this `@JRubyMethod JrubyAckedWriteClientExt create` method.

Removed and tested on local, will push changes soon and update here.

File: logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java [hunk 19]
```diff
@@ -792,8 +807,9 @@ private void releaseLockAndSwallow() {
     /**
      * return the {@link Page} for the next read operation.
      * @return {@link Page} will be either a read-only tail page or the head page.
+     * @throws QueueRuntimeException if queue is closed
      */
-    public Page nextReadPage() {
+    private Page nextReadPage() {
```
[the remark this answers is not in the document]
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java:813]: My opinion: if not acquired by current thread, we should let it try again. `IllegalStateException` breaks the process, so `QueueRuntimeException` seems better. How do you think?

File: logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (mashhurs) [reply logstash-core/src/main/java/org/logstash/ext/JrubyAckedWriteClientExt.java]: Removed the method since unused.

**Review by yaauie — COMMENTED** [review]
I had a couple outstanding issues that I have addressed in commits that I have pushed to your branch:

 - `Queue#nonBlockReadBatch` did not have a closed-queue check; we discussed either adding the closed-queue check to _both_ the blocking and non-blocking methods _OR_ placing the closed-queue check in the private `Queue#nextReadPage` that is shared by both of them. I resolved this in 790cb1873 with the latter option
 - `Queue#nextReadPage` being called without exclusive ownership of the lock is an illegal state that cannot be recovered from, because it allows the private method to leak `Page` to a caller that does not have exclusive access. This is a scenario that cannot be reached with the current code-base because both callers of this private method do so with exclusive access, but if our code ever changes to break this promise an `IllegalStateException` will better guide us during the development process before we commit. I have resolved this in 0a485f074

**Comment by yaauie** [comment]
@robbavey review notes:

When an upstream Pipeline Output sends events to a downstream Pipeline Input, and the downstream Pipeline Input's queue is either closed or closing, the resulting attempt to write to the queue causes a variety of exceptions that are not handled by the intermediate PipelineBus, cascading through to crash the upstream Pipeline:

 - an attempt to write after the queue-close has been initiated resulted in in unhandled `IllegalStateException`
 - a queue becoming closed between the writer's closed-queue check and that writer acquiring the lock to perform the write results in unspecified behavior that could either corrupt the queue or an unhandled NPE dereferencing the `Queue.headPage` after it has been cleaned up.

The primary action of this PR is to push the queue-closed guards for both reads and writes down to the `Queue` itself _inside_ the already-locking methods, so that a queue _cannnot_ be effectively closed between the guard and the action that requires guarding. Both condition variables for the lock effectively also check the queue-closed state when waking from a `Condition#await`, and expensive operations like serialization are still done outside the lock.

***

Separately, the resume-from-failure logic in the PipelineBus had an issue that could result in _duplicate_ processing when encountering multiple partial failures while writing to the downstream, because it used the last failure position of the failed subset without accounting for the offset of that subset from the batch as a whole.

File: logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java [hunk 20]
```diff
@@ -81,11 +81,10 @@ public void sendEvents(final PipelineOutput sender,
                         if (lastResponse != null && lastResponse.getStatus() == PipelineInput.ReceiveStatus.FAIL) {
                             // when last call to internalReceive generated a fail, restart from the
                             // fail position to avoid reprocessing of some events in the downstream.
-                            lastFailedPosition = lastResponse.getSequencePosition();
-
-                            logger.warn("Attempted to send event to '{}' but that address reached error condition. " +
-                                    "Will Retry. Root cause {}", address, lastResponse.getCauseMessage());
-
+                            // we get 0~clones.length position on failure, keep tracking failed position to correctly copy from original orderedEvents
```
Comment (robbavey) [inline logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java:84]: Should this read `clones.length`?

**Review by robbavey — COMMENTED** [review]
A few nits on naming, and a few questions.

- Should we take the opportunity while we're here to add more debug or even trace logging - 
there are a few areas where there is no logging (nothing in `close`, for example, and `openPages` has a few unlogged code paths)
- Is this [close method](https://github.com/elastic/logstash/blob/790cb1873cec05897cb455eb92546a9dc3f6634e/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L214) superfluous, as it gets called in the calling method regardless
- Do we need to follow up on [this todo](https://github.com/elastic/logstash/blob/790cb1873cec05897cb455eb92546a9dc3f6634e/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L764)? [notFull.await](https://github.com/elastic/logstash/blob/790cb1873cec05897cb455eb92546a9dc3f6634e/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L461) does not have a timeout, so will never exit if part of the closing logic throws

File: logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java (hunk 20 above)
Comment (yaauie) [reply logstash-core/src/main/java/org/logstash/plugins/pipeline/PipelineBus.java]: I think this is meant to express the range of `0` to `clones.length` (differentiated from the range `0` to `orderedEvents.length`), but I have addressed it in e2cf5a03e

**Comment by yaauie** [comment]
> A few nits on naming

Nitpicks about constant names addressed in 35a12c330

> [...] and a few questions

The general theme is that I am wary of growing the scope and delaying the delivery of a fix for problems that are known to be experienced in the wild.

> * Should we take the opportunity while we're here to add more debug or even trace logging -
>   there are a few areas where there is no logging (nothing in `close`, for example, and `openPages` has a few unlogged code paths)

While I think more logging would be helpful, I think it is out-of-scope for this PR and I don't want its inclusion to delay the fix for known issues being included.

> * Is this [close method](https://github.com/elastic/logstash/blob/790cb1873cec05897cb455eb92546a9dc3f6634e/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L214) superfluous, as it gets called in the calling method regardless

Maybe. But the scope of this PR is not meant to be a full audit and I am wary of growing the scope and delaying the known fixes being available.

> * Do we need to follow up on [this todo](https://github.com/elastic/logstash/blob/790cb1873cec05897cb455eb92546a9dc3f6634e/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L764)? [notFull.await](https://github.com/elastic/logstash/blob/790cb1873cec05897cb455eb92546a9dc3f6634e/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L461) does not have a timeout, so will never exit if part of the closing logic throws

I don't believe so, at least not in this PR. It would be good to do an audit, but the changes here have should have net zero effect on the code in question.

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by yaauie** [comment]
@logstashmachine backport 8.9
