### PR TITLE
revert #11482 and fix redundant code generation

### LINKED ISSUE #11560: multiple pipelines startup slowdown regression introduced in 7.5.2
The is a significative slowdown in starting logstash introduced in 7.5.2 **when using multiple pipelines**. We are investigating the issue.

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #11560 

The fix for the Java execution slowdown relative to the number of worker in #11482 introduced a regression when using multiple pipelines. By analyzing the regression we realized that although the fix was solving the problem for the single pipeline with multiple workers it actually did not correctly solve the root cause of the problem. By removing the global class cache it prevented cross-pipelines class caching, which resulted in the regression.

This PR reverts the previous fix and correctly address the root cause. The real problem was that the  configuration Java code was being generated multiple times through the `hashCode()` and `equals()` methods which were calling the `normalizedSource()` method multiple times.  The fix addresses this by memoizing the `hashCode()` and `normalizedSource()` methods. A few other optimizations have also been made.

The result is that the multiple worker slowdown is still solved and the regression is also fixed.

### CODE REVIEW

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java [hunk 1]
```diff
@@ -33,84 +32,98 @@
...
+    public T instantiate() {
+         try {
+            synchronized (COMPILER) {
+                Class<? extends Dataset> clazz = CLASS_CACHE.get(this);
+                if (clazz == null) {
+                    clazz = compile();
+                    CLASS_CACHE.put(this, clazz);
+                }
+                return (T) clazz.getConstructor(Map.class).newInstance(ctorArguments());
+            }
```
Comment (colinsurprenant) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: I tried to use a `ConcurentHashMap` and use `computeIfAbsent` for the `compile()` result but both the compilation **and** `newInstance()` call need to be both in the same exclusive context otherwise there are some race condition issues.

Comment (kares) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: do you feel like this might eventually be a bottleneck (given that you sized the class cache map to 5000) ?

Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: - Note that this is basically how this was (the global lock) before (in 7.5.1). It is certainly a bottleneck, but ATM I don't see a way around it. For a cross-pipeline and cross-workers cache to be efficient (to globally avoid double-compilations) no 2 compilations should ne performed concurrently. Also, the `cook` call, the `setParentClassLoader` call and the generated class instantiation must be done atomically  (for reasons I do not yet grasp).
- This bottleneck mostly hurts in in the mutli-pipelines scenario, at initial startup where there are a lot more chances of needing to perform an actual compilation. 
- I put in an initial capacity of 5000 because the default initial capacity of 16 is definitely too small, any decent config endup generating tons of classes. 5000 is arbitrary. 
- Not that there is currently a cache eviction leak problem with this code because it will not evict dead classes across pipelines reloads. This problem was already present in 7.5.1 and I decided not to tackle it just now because practically speaking I do not think the cache should grow at a rate where that leak could have an impact. I will document that problem in the code and open a followup issue about it too.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java [hunk 2]
```diff
@@ -33,84 +32,98 @@
...
-            return (T) clazz.<T>getConstructor(Map.class).newInstance(ctorArguments());
+    public T instantiate() {
+         try {
+            synchronized (COMPILER) {
+                Class<? extends Dataset> clazz = CLASS_CACHE.get(this);
+                if (clazz == null) {
+                    clazz = compile();
+                    CLASS_CACHE.put(this, clazz);
+                }
+                return (T) clazz.getConstructor(Map.class).newInstance(ctorArguments());
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: Does instantiation need to be inside the global compiler lock?

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java [hunk 3]
```diff
@@ -33,84 +32,98 @@
...
-                }
-                COMPILER.setParentClassLoader(COMPILER.getClassLoader());
-                clazz = (Class<? extends Dataset>)COMPILER.getClassLoader().loadClass(
-                        String.format("org.logstash.generated.%s", name)
-                );
-
-                return clazz;
-            } catch (final CompileException | ClassNotFoundException | IOException ex) {
-                throw new IllegalStateException(ex);
+    private  Class<? extends Dataset> compile() {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: Let's leave a note about the need for synchronization on `COMPILER` here, maybe something like:

```suggestion
    /**
     * This method is NOT thread-safe, and must have exclusive access to `COMPILER`
     * so that the resulting `ClassLoader` after each `SimpleCompiler#cook()` operation
     * can be teed up as the parent for the next cook operation.
     */
    private  Class<? extends Dataset> compile() {
```

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java [hunk 4]
```diff
@@ -33,84 +32,98 @@
...
+        final Class<T> interfce)
+    {
         this.methods = methods;
         this.fields = fields;
         type = interfce;
-        classSeq = classSeqCount.incrementAndGet();
+
+        // normalizes away the name of the class so that two classes of different name but otherwise
+        // equivalent syntax get correctly compared by {@link #equals(Object)}.
+        normalizedSource = generateCode(CLASS_NAME_PLACEHOLDER);
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: :+1:

While I generally cringe at executing complex code like this in a constructor, the resulting value is intrinsically tied to the _identity_ of this object and deferring it to a separate method that we call out to in a synchronized in several places to make that work would only serve to obfuscate this fact.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 2 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: I believe it has for reasons I do not yet grasp. After trying different strategy, moving the instantiation outside the lock resulted in class loading problems when using multiple pipelines. I'll reassess to make sure these were not the result of other related changes.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 3 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: agree.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 4 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: same same. I had it lazily initialized before but figured that the lazy initialization had no real value here and just added a bit of unnecessary code and complexity. 
As per you other comment this overall code-gen and compilation strategy should probably by  re evaluated which will result in probably decoupling some of that code here.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 2 above)
Comment (yaauie) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: if it is, calling out that it is necessary in a comment may be a useful breadcrumb for the next time we have to deal with this section of code.

Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: absolutely, will do.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 3 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: done

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 2 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: so, good news, after looking into it it seems I may have confused that problem with other changes. I refactored the code and the instantiation is now outside the lock and all my tests and the integration tests are passing.
This opens open up the door to try using a compilation `ReadWriteLock` so that compiling a class will not interfere with other instantiations of compiled class.

Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: closing this conversation, we can open a new one on the new code.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 1 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java]: resolving this conversation, will followup with an eviction issue.

**Comment by colinsurprenant** [comment]
- I revisited the need to have the instantiation inside the compile lock and I did not understand why it was required probably for good reasons because it does not look like it is required. My previous tests for that probably included other changes which created other concurrency issues. 

- As it is now, using the `COMPILER.synchronize` is basically equivalent to just synchronizing the method.

- Now that we know that instantiation does not need to be in that synchronization, I tried using a `ReadWriteLock`, the logic being that multiple threads should be able to concurrently read the cache for already compiled classes. The problem we still have is that the write side of actually performing the compilation is disproportionate to the read side, so every time a write/compilation is performed, everything is locked. 

Here's a test implementation of using a `ReentrantReadWriteLock`, which follows the Javadoc sample usage example. 

```
    private  Class<? extends Dataset> compile() {
        try {
            COMPILE_LOCK.readLock().lock();

            Class<? extends Dataset> clazz = CLASS_CACHE.get(this);
             if (clazz == null) {
                // must release read lock before acquiring write lock
                COMPILE_LOCK.readLock().unlock();
                COMPILE_LOCK.writeLock().lock();
                try {
                    // recheck state because another thread might have
                    // acquired write lock and changed state before we did.
                    clazz = CLASS_CACHE.get(this);
                    if (clazz == null) {
                        final String name = String.format("CompiledDataset%d", CLASS_CACHE.size());
                        final String code = CLASS_NAME_PLACEHOLDER_REGEX.matcher(normalizedSource).replaceAll(name);
                        if (SOURCE_DIR != null) {
                            final Path sourceFile = SOURCE_DIR.resolve(String.format("%s.java", name));
                            Files.write(sourceFile, code.getBytes(StandardCharsets.UTF_8));
                            COMPILER.cookFile(sourceFile.toFile());
                        } else {
                            COMPILER.cook(code);
                        }
                        COMPILER.setParentClassLoader(COMPILER.getClassLoader());
                        clazz = (Class<T>) COMPILER.getClassLoader().loadClass(
                                String.format("org.logstash.generated.%s", name)
                        );
                        CLASS_CACHE.put(this, clazz);
                    }
                    // downgrade by acquiring read lock before releasing write lock
                    COMPILE_LOCK.readLock().lock();
                } finally {
                    // unlock write, still hold read
                    COMPILE_LOCK.writeLock().unlock();
                }
            }
            COMPILE_LOCK.readLock().unlock();
            return clazz;
        } catch (final CompileException | ClassNotFoundException | IOException ex) {
            throw new IllegalStateException(ex);
        }
    }
```

So far it seems to be working correctly but I have not seen any significant performance difference with my local tests. WDYT?

I will try a variation where the actual compilation will happen outside the write lock, which will help not holding the write lock for too long at the potential cost of performing multiple compilations.

**Comment by colinsurprenant** [comment]
@yaauie I think we should move on with the current *simpler* and straightforward synchronization (pending LGTM) for the sake of moving forward with a correct solution with solves the regression to unblock 7.6. Further optimization work can be worked on in another PR.

**Comment by colinsurprenant** [comment]
Merging in master, backports for 7.7, 7.6, 7.5.3
