### PR TITLE
Avoid to itereate with each_index

### LINKED ISSUE #12760: TAGS option used in azure input crash Logstash
- Version: 7.10.0
- Operating System:
- Config File:
```
input {
    azure_event_hubs {
    event_hub_connections => ["Endpoint=sb://logstash.windows.net/;SharedAccessKeyName=activity-log-read-only;SharedAccessKey=blabla;EntityPath=ops-logs"]
    decorate_events => true
    consumer_group => "logstash"
    storage_connection => "DefaultEndpointsProtocol=https;AccountName=logstash;AccountKey=whywhywhy;EndpointSuffix=core.windows.net"
    storage_container => "logstash"
    tags => ["THIS_IS_A_TAG"]
  }
}
output {
	stdout{
		codec => rubydebug
	}
}
```
- Sample Data:
- Steps to Reproduce:
 -  run Logstash 7.10.0 with the above configuration

With Logstash version `7.9.3` the above configuration reports the error:
```
[2021-03-22T11:19:20,665][ERROR][logstash.inputs.azureeventhubs][main][1929f18cc145e88f794eaf0593d66a529b5dbe30a8244c586e3fa634408e2f22] Event Hub failed during initialization. 
	{:event_hub_name=>"ops-logs", 
	:exception=>java.lang.RuntimeException: Failure initializing Storage lease manager, 
	:backtrace=>["com.microsoft.azure.eventprocessorhost.EventProcessorHost.registerEventProcessorFactory(com/microsoft/azure/eventprocessorhost/EventProcessorHost.java:480)", 
                 "jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", 
                 "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)", 
                 "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", 
                 "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)", 
                 "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)", 
                 "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)", 
                 "home.andrea.workspace.elastic_products.logstash_minus_7_dot_9_dot_3.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_input_minus_azure_event_hubs_minus_1_dot_2_dot_2.lib.logstash.inputs.azure_event_hubs.run(/tmp/logstash-7.9.3/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_event_hubs-1.2.2/lib/logstash/inputs/azure_event_hubs.rb:430)",                  
                 "org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)", 
                 "java.lang.Thread.run(java/lang/Thread.java:834)"]}
[2021-03-22T11:19:20,847][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-03-22T11:19:21,679][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2021-03-22T11:19:22,222][INFO ][logstash.runner          ] Logstash shut down.
```

which is expected becauee the credentials are not correct, but starting with version `7.10.0` it returns an exception related to `tags` options that's not raised  with other inputs (like `tcp-input`) when `tags` is used.

```
[2021-03-22T11:19:43,880][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2021-03-22T11:19:45,170][INFO ][org.reflections.Reflections] Reflections took 36 ms to scan 1 urls, producing 23 keys and 47 values 
[2021-03-22T11:19:45,452][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::IllegalStateException", 
	:message=>"Unable to configure plugins: (NoMethodError) undefined method `each_index' for <Java::JavaUtil::ArrayList:-2028450873 [\"THIS_IS_A_TAG\"]>:Java::JavaUtil::ArrayList", 
	:backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:119)", 
            "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:83)", 
            "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", 
            "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", 
            "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169)", 
            "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuperSplatArgs(IRRuntimeHelpers.java:1156)", 
            "org.jruby.ir.targets.InstanceSuperInvokeSite.invoke(InstanceSuperInvokeSite.java:39)", 
            "home.andrea.workspace.elastic_products.logstash_minus_7_dot_10_dot_1.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$initialize$0(/tmp/logstash-7.10.1/logstash-core/lib/logstash/java_pipeline.rb:47)", 
            "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", 
            "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", 
            "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)", 
            "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:86)", 
            "org.jruby.RubyClass.newInstance(RubyClass.java:939)", 
            "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", 
            "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", 
            "home.andrea.workspace.elastic_products.logstash_minus_7_dot_10_dot_1.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0(/tmp/logstash-7.10.1/logstash-core/lib/logstash/pipeline_action/create.rb:52)", 
            "home.andrea.workspace.elastic_products.logstash_minus_7_dot_10_dot_1.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0$__VARARGS__(/tmp/logstash-7.10.1/logstash-core/lib/logstash/pipeline_action/create.rb)", 
            "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", 
            "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", 
            "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", 
            "home.andrea.workspace.elastic_products.logstash_minus_7_dot_10_dot_1.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/tmp/logstash-7.10.1/logstash-core/lib/logstash/agent.rb:365)", 
            "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", 
            "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", 
            "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", 
            "org.jruby.runtime.Block.call(Block.java:139)", 
            "org.jruby.RubyProc.call(RubyProc.java:318)", 
            "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", 
            "java.base/java.lang.Thread.run(Thread.java:834)"]}
warning: thread "Converge PipelineAction::Create<main>" terminated with exception (report_on_exception is true):
LogStash::Error: Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`
          create at org/logstash/execution/ConvergeResultExt.java:129
             add at org/logstash/execution/ConvergeResultExt.java:57
  converge_state at /tmp/logstash-7.10.1/logstash-core/lib/logstash/agent.rb:378
```

It seems not directly related to any changes in the Azure plugin since both Logstash versiosn uses the `1.2.2` version of the plugin.

Related to https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues/64

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

Fix a crash of Logstash in initialization when using the `logstash-input-azure_eventhub`.

## What does this PR do?

Sometime the deep_replace could be invoked by plugins, using the LogStash::Config::Mixin#validate.
This method receives a Ruby hash which could contains Java ArrayList instead of Ruby Array.
The iteration method `each_index` is not available for ArrayList, so resort to someform of plain old way.

## Why is it important/What is the impact to the user?

Fixes problem with some plugins, like `input-azure_eventhub` liek described in #12760

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

- Closes #12760

### CODE REVIEW

**Comment by andsel** [comment]
Jenkins test this please

File: logstash-core/lib/logstash/util/substitution_variables.rb [hunk 1]
```diff
@@ -37,8 +37,10 @@ def deep_replace(value)
       end
     else
       if value.is_a?(Array)
-        value.each_index do | valueArrayIndex|
-          value[valueArrayIndex] = deep_replace(value[valueArrayIndex])
+        valueArrayIndex = 0
+        value.each do |single_value|
+          value[valueArrayIndex] = deep_replace(single_value)
+          valueArrayIndex += 1
```
Comment (yaauie) [inline logstash-core/lib/logstash/util/substitution_variables.rb:43]: Styleguide nitpick: use snake_case for variables in ruby code

```suggestion
        value_array_index = 0
        value.each do |single_value|
          value[value_array_index] = deep_replace(single_value)
          value_array_index += 1
```

**Review by yaauie — COMMENTED** [review]
This feels like a bug that needs to be reported upstream to JRuby. If an object responds true to ruby `Object#is_a?(Array)`, we should be able to expect it to _behave_ like a ruby `Array`, complete with ruby `Enumerable` support.

**Comment by andsel** [comment]
I don't know if it's a JRuby bug with the following script:
```ruby
#!/bin/ruby

ja = Java::JavaUtil::ArrayList.new
ja << 1
if ja.is_a?(Array)
  puts "Ok, it's like a RubyArray"
  ja.each_index do |value_idx|
  	puts "processing value: #{ja[value_idx]}"
  end	
else
  puts "Sorry, java ArrayList is not seen as a RubyArray"  
end
```
I hit that ArrayList is not a Ruby's array, so I don't know if it's a JRuby problem.

```
$ ruby -v
jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +jit [linux-x86_64]
```

File: logstash-core/lib/logstash/util/substitution_variables.rb [hunk 2]
```diff
@@ -37,8 +37,10 @@ def deep_replace(value)
       end
     else
       if value.is_a?(Array)
-        value.each_index do | valueArrayIndex|
-          value[valueArrayIndex] = deep_replace(value[valueArrayIndex])
+        value_array_index = 0
+        value.each do |single_value|
+          value[value_array_index] = deep_replace(single_value)
+          value_array_index += 1
```
Comment (kares) [inline logstash-core/lib/logstash/util/substitution_variables.rb:43]: :+1: much better than the original, for explanation 
`value.is_a? Array` is true for any `java.util.Collection` instance
which is really BAAAD but existed for a long time: https://github.com/elastic/logstash/blob/v7.12.0/logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java#L143-L145

maybe this could be simplified using `each_with_index` (which is provided on all `Enumerable`s and thus will also work on `java.util.Collection` types) e.g.
```suggestion
        value.each_with_index do |single_value, i|
          value[i] = deep_replace(single_value)
```
... it's still ugly to be iterating and changing the contents at the same time but this is what we've started with

**Review by kares — APPROVED** [review]
LGTM, 

a minor suggestion on using one line less but no strong feelings `each` works as well

a side note: this code will break again as soon as a non List collection is passed in from somewhere e.g. `java.util.HashSet` (since it won't have the `collection[i] = ` method)

**Review by yaauie — APPROVED** [review]
Oof. I didn't know about [these monkey-patches](https://github.com/elastic/logstash/blob/94d04f8044b88ebab1e9cabde0a3eada8c446107/logstash-core/src/main/java/org/logstash/RubyJavaIntegration.java). You're right, this isn't an upstream JRuby bug -- it's a Logstash one. While the jruby proxy for `java.util.Collection` has _some_ overlap with the method signatures of `org.jruby.RubyArray`, our monkey-patch to say that it _is_ a `org.jruby.RubyArray` introduce opportunities for bugs like these.

These changes LGTM. In my mind, they solve one particular _effect_ of the bug, and not the bug itself.

**Comment by yaauie** [comment]
Note: the customer should upgrade to 7.17.1, which is currently the latest patch release in the 7.17 minor series.
