### PR TITLE
Fix Reflections stack traces when process yml files in classpath and …

### LINKED ISSUE #12992: Reflections library print a stacktrace in debug log about alises yml files
**Logstash information**:

Please include the following information:

1. Logstash version: 8.0.0-SNAPSHOT
2. Logstash installation source: sources
3. How is Logstash being run `bin/logstash` after a `./gradlew assemble` from sources

~~**Plugins installed**: (`bin/logstash-plugin list --verbose`)~~

~~**JVM** (e.g. `java -version`):~~

~~**OS version** (`uname -a` if on a Unix-like system):~~

**Description of the problem including expected versus actual behavior**:
When run `bin/logstash --log.level debug` the console contains errors like:
```
ar:file:/home/andrea/workspace/logstash_andsel/logstash-core/lib/jars/logstash-core.jar!/
[2021-06-16T09:54:30,572][DEBUG][org.reflections.Reflections] could not scan file org/logstash/plugins/plugin_aliases.yml in url jar:file:/home/andrea/workspace/logstash_andsel/logstash-core/lib/jars/logstash-core.jar!/ with scanner SubTypesScanner
org.reflections.ReflectionsException: could not create class object from file org/logstash/plugins/plugin_aliases.yml
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections.scan(Reflections.java:253) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.scan(Reflections.java:202) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:123) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:168) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:141) [reflections-0.9.11.jar:?]
	at org.logstash.plugins.discovery.PluginRegistry.discoverPlugins(PluginRegistry.java:83) [logstash-core.jar:?]
	at org.logstash.plugins.discovery.PluginRegistry.<init>(PluginRegistry.java:65) [logstash-core.jar:?]
	at org.logstash.plugins.discovery.PluginRegistry.getInstance(PluginRegistry.java:72) [logstash-core.jar:?]
	at org.logstash.plugins.factory.PluginFactoryExt.<init>(PluginFactoryExt.java:86) [logstash-core.jar:?]
	at org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:73) [logstash-core.jar:?]
	at org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuperSplatArgs(IRRuntimeHelpers.java:1156) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.ir.targets.InstanceSuperInvokeSite.invoke(InstanceSuperInvokeSite.java:39) [jruby-complete-9.2.19.0.jar:?]

```

**Steps to reproduce**:

 1. run `bin/logstash -e "input {stdin{}} output{stdout{ codec => rubydebug}}" --debug`
 2. check the console
 

~~**Provide logs (if relevant)**:~~

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

[rn:skip]

## What does this PR do?

Adds a filter to Reflections library when it scan `org.logstash.plugins` to include only `.class` files and avoid to load and process AliasRegistry.yml and plugin_aliases.yml. Fixes #12992 

## Why is it important/What is the impact to the user?

Avoid to see stacktrace error when Logstash is run in debug

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [x] try a local run and see that not stacktraces heppears

## How to test this PR locally

Run Logstash with `bin/logstash -e "input {stdin{}} output{stdout{ codec => rubydebug}}" --log.level debug` and check no stacktraces are present in console.

## Related issues

- Fixes #12992 

## Logs

```
[2021-06-16T09:54:30,572][DEBUG][org.reflections.Reflections] could not scan file org/logstash/plugins/plugin_aliases.yml in url jar:file:/home/andrea/workspace/logstash_andsel/logstash-core/lib/jars/logstash-core.jar!/ with scanner SubTypesScanner
org.reflections.ReflectionsException: could not create class object from file org/logstash/plugins/plugin_aliases.yml
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32) ~[reflections-0.9.11.jar:?]
	at org.reflections.Reflections.scan(Reflections.java:253) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.scan(Reflections.java:202) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:123) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:168) [reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:141) [reflections-0.9.11.jar:?]
	at org.logstash.plugins.discovery.PluginRegistry.discoverPlugins(PluginRegistry.java:83) [logstash-core.jar:?]
	at org.logstash.plugins.discovery.PluginRegistry.<init>(PluginRegistry.java:65) [logstash-core.jar:?]
	at org.logstash.plugins.discovery.PluginRegistry.getInstance(PluginRegistry.java:72) [logstash-core.jar:?]
	at org.logstash.plugins.factory.PluginFactoryExt.<init>(PluginFactoryExt.java:86) [logstash-core.jar:?]
	at org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:73) [logstash-core.jar:?]
	at org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuperSplatArgs(IRRuntimeHelpers.java:1156) [jruby-complete-9.2.19.0.jar:?]
	at org.jruby.ir.targets.InstanceSuperInvokeSite.invoke(InstanceSuperInvokeSite.java:39) [jruby-complete-9.2.19.0.jar:?]
	at home.andrea.workspace.logstash_andsel.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$initialize$0(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:47) [jruby-complete-9.2.19.0.jar:?]
Caused by: org.reflections.ReflectionsException: could not create class file from plugin_aliases.yml
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:102) ~[reflections-0.9.11.jar:?]
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24) ~[reflections-0.9.11.jar:?]
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30) ~[reflections-0.9.11.jar:?]
	... 36 more
Caused by: java.io.IOException: bad magic number: 23434845
	at javassist.bytecode.ClassFile.read(ClassFile.java:790) ~[javassist-3.26.0-GA.jar:?]
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:185) ~[javassist-3.26.0-GA.jar:?]
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100) ~[reflections-0.9.11.jar:?]
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24) ~[reflections-0.9.11.jar:?]
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30) ~[reflections-0.9.11.jar:?]
	... 36 more

```

### CODE REVIEW

File: logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java [hunk 1]
```diff
@@ -80,7 +84,12 @@ public static PluginRegistry getInstance(AliasRegistry aliasRegistry) {
     private void discoverPlugins() {
         // the constructor of Reflection must be called only by one thread, else there is a
         // risk that the first thread that completes close the Zip files for the others.
-        Reflections reflections = new Reflections("org.logstash.plugins");
+        // filter from processing all resources present in package classpath that are not classes.
```
Comment (kaisecheng) [inline logstash-core/src/main/java/org/logstash/plugins/discovery/PluginRegistry.java:87]: suggestion
// scan all .class present in package classpath

**Review by kaisecheng — APPROVED** [review]
I have tested locally and confirmed the `ReflectionsException` exception has gone. A suggestion for the comment, otherwise LGTM. Thanks for the quick fix.
