### PR TITLE
fix for accessors lut invalidation

### LINKED ISSUE #5127: Accessors path invalidation problem
This problem was originally reported by @guyboertje in #5212. I am copying the invalidation bug sequence here:

```sh
> event = LogStash::Event.new
=> #<LogStash::Event:0x25ce435 @metadata_accessors=#<LogStash::Util::Accessors:0x7ea71fc2 @store={}, @lut={}>, @cancelled=false, @data={"@version"=>"1", "@timestamp"=>"2016-04-15T14:19:31.561Z"}, @metadata={}, @accessors=#<LogStash::Util::Accessors:0x7cd5fcf4 @store={"@version"=>"1", "@timestamp"=>"2016-04-15T14:19:31.561Z"}, @lut={}>>
> event["[a][0]"]
=> nil
> event["[a][0]"] = 42
=> 42
> event["[a]"]
=> {"0"=>42}
> event["[a]"] = [42,24]
=> [42, 24]
> event["[a]"]
=> [42, 24]
> event["[a][0]"]
=> 42
> event["[a]"] = [24,42]
=> [24, 42]
> event["[a][0]"]
=> 42
> event["[a][0]"] = {"a"=> 99, "b" => 98}
=> {"a"=>99, "b"=>98}
> event["[a][0]"]
=> {"a"=>99, "b"=>98}
> event["[a]"]
=> [24, 42]
> event["[a][0]"]
=> {"a"=>99, "b"=>98}
> event["[a][0][b]"]
TypeError: can't convert String into Integer
  from org/jruby/RubyFixnum.java:1143:in `[]'
```

I wrote a spec with this sequence and confirm the problem on **both** the Ruby and Java Event implementations.

### PR DESCRIPTION
**Pull request by colinsurprenant**
This is a fix for the Accessors fieldref cache invalidation in the Ruby Event only. Before considering merging this we should assess the performance impact and see if using a hierarchical cache would provide better performance. Depending on the direction we choose for the fix, the same idea will have to be applied to the Java Event.

A stale cache spec has been added. 

Fixes #5127 

**[edit 04/20]**
Per comments below, we agreed that this fix is acceptable performance-wise and the same fix has been applied to the Java Event. Doing so uncovered another bug that resulted in a `expecting List or Map ` ClassCastException, also fixed and related test added.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
Ah yes, obviously, you have to make sure `logstash-core-event` is selected in the `Gemfile` and `logstash-core.gemspec`

**Comment by jsvd** [comment]
From my benchmarks of operations on LogStash::Event, the performance change with this patch is as follows:
* in a set-heavy benchmark, this patch is ~7% __faster__ than the current implementation
* in a read-heavy benchmark, this patch is ~4.8%  __slower__ than current implementation
* in a mixed benchmark, this patch is ~4.5% __faster__ than the current implementation

All these are measured with an uncertainty around +/- 4%

So IMO, since this actually fixes a bug, I think the PR is on the right track 👍

**Comment by colinsurprenant** [comment]
@jsvd thanks for measuring this!

**Comment by colinsurprenant** [comment]
- We agreed that this fix is acceptable performance-wise and the same fix has been applied to the Java Event.
- Doing so uncovered another bug that resulted in a `expecting List or Map ` ClassCastException, also fixed and related test added.

Note that `rake test:core` reports the error under both Event implementations if/when removing the fix. The Java implementation also includes specific Java unit tests.

@jsvd @guyboertje @tal please review?

**Comment by colinsurprenant** [comment]
The build failure is not related to this PR
```
Failures:

  1) LogStash::Agent metrics after config reloading resets the metric collector
     Failure/Error: expect(snapshot.metric_store.get_with_path("/stats/events")[:stats][:events][:in].value).to eq(new_config_generator_counter)
     NoMethodError:
       undefined method `value' for nil:NilClass
     # ./logstash-core/spec/logstash/agent_spec.rb:374:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'

Finished in 38.1 seconds (files took 2.1 seconds to load)
1179 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/agent_spec.rb:359 # LogStash::Agent metrics after config reloading resets the metric collector

Randomized with seed 54320
```
@ph @purbon  ?

**Comment by ph** [comment]
@colinsurprenant I will look into this failling test. first time I see it.

File: logstash-core-event/spec/logstash/event_spec.rb [hunk 1]
```diff
@@ -602,4 +602,33 @@
       expect(event1.to_s).to eq("#{timestamp.to_iso8601} #{event1["host"]} #{event1["message"]}")
     end
   end
+
+  describe "Accessors invalidation" do
+    let(:event) { LogStash::Event.new({ "message" => "foo" }) }
+
+    it "should perperly invalidate accessors" do
```
Comment (guyboertje) [inline logstash-core-event/spec/logstash/event_spec.rb]: properly

**Comment by guyboertje** [comment]
LGTM

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java [hunk 2]
```diff
@@ -67,7 +67,7 @@ private Object findTarget(FieldReference field) {
         target = this.data;
         for (String key : field.getPath()) {
             target = fetch(target, key);
-            if (target == null) {
+            if (! targetIsCollection(target)) {
```
Comment (jsvd) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: this method only checks that the argument is a collection, I suggest renaming it as `isCollection`

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java [hunk 3]
```diff
@@ -134,7 +138,7 @@ private Object fetch(Object target, String key) {
         } else if (target == null) {
             return null;
         } {
-            throw new ClassCastException("expecting List or Map");
+            throw new ClassCastException("expecting List or Map, found " + target.getClass().toString());
```
Comment (jsvd) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: for consistency sake I suggest either putting or not having a comma on these log messages

**Comment by jsvd** [comment]
2 minor comments, otherwise tests went well, LGTM

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java (hunk 2 above)
Comment (colinsurprenant) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: I was totally expecting this comment :D

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java (hunk 3 above)
Comment (colinsurprenant) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: +1

File: logstash-core-event/spec/logstash/event_spec.rb (hunk 1 above)
Comment (colinsurprenant) [inline logstash-core-event/spec/logstash/event_spec.rb]: 👍

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java [hunk 4]
```diff
@@ -134,7 +138,7 @@ private Object fetch(Object target, String key) {
         } else if (target == null) {
             return null;
         } {
```
Comment (colinsurprenant) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: woa, this is a weird syntax quirk

Comment (talevy) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: missing else

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java [hunk 5]
```diff
@@ -98,7 +102,7 @@ private Object findCreateTarget(FieldReference field) {
                 } else if (target == null) {
                     // do nothing
                 } else {
```
Comment (talevy) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: make this `else if (target != null)` and remove above empty block?

Comment (colinsurprenant) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: +1

File: logstash-core-event-java/src/main/java/com/logstash/Accessors.java (hunk 4 above)
Comment (colinsurprenant) [inline logstash-core-event-java/src/main/java/com/logstash/Accessors.java]: yup... weird omission, it was still "correct" but ... anyhow. fixing :D

**Comment by colinsurprenant** [comment]
ok, pushed changes. any final review @jsvd @talevy ?

**Comment by jsvd** [comment]
LGTM

**Comment by colinsurprenant** [comment]
merged in master, 5.0, 2.x. will wait after 2.3.2 release (today) to merge fix in 2.3, we prefer to get a bit more mileage with this fix before it makes it into a release.
