### PR TITLE
dynamically get the plugin id instead of hardcoding it in the generated classes

### LINKED ISSUE #12031: Pipeline compilation significantly increased in 7.7.0 in comparison to 7.6.2
- Version: `7.7.0`, `7.7.1`, `7.8.0`
- Operating System: any

Starting from Logstash `7.7` was released a feature to put the in logs also the `plugin.id` to help debugging of problems with pipelines (PR #11078 and #11593) that changed required to "decorate" each plugin invocation with code to set/unset the ThreadLocal with `plugin.id` (https://github.com/elastic/logstash/commit/7a2222046795e28cb8ec31bcc4c2c113225fd1ff#diff-aa66540c4668f70bc7568433f4dac1efR155 and https://github.com/elastic/logstash/commit/7a2222046795e28cb8ec31bcc4c2c113225fd1ff#diff-aa66540c4668f70bc7568433f4dac1efR172). This introduction of more SythaxElements is causing slow downs in pipeline compilations, introducing a potential regression.

To test it is sufficient to create a pipeline with 500 mutate filters (same filter replicated 500 times) and the pipeline bring more time to be compile in version `7.7` then in version `7.6.2`

In some test pipelines we have spot this increment of pipeline compilation times:
|                   |  `7.6.2`  |      `7.7.1`     |
|----------------|------------|------------------|
| 1 pipeline   | ~3 mins | ~5 mins       |
| 2 pipelines | ~3 mins | ~17 mins     |
| 3 pipelines | ~3 mins | ~37 mins     |
| 4 pipelines | ~3 mins | ~1h 13 mins|

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #12031 

This PR fixes the regression introduced in 7.7.0 where the plugin id was set in the thread context  by hard coding the unique plugin id in the generated class resulting in generating non cacheable classes that all contained a unique id. 

The fix is to dynamically get the plugin id from the plugin instance field which result in non-unique generated code and thus allowing the reuse of equivalent generated classes. 

- Before this PR the generated filter and output classes would contain code similar to 
```
org.apache.logging.log4j.ThreadContext.put("plugin.id", "ce80c1c692c7fd1664e67aa37b9b5ee8f6d7fa336b22bad5b14684ca44132adc");
```

- This PR make that code be like:
```
org.apache.logging.log4j.ThreadContext.put("plugin.id", field1.getId().toString());
```

### CODE REVIEW

**Comment by andsel** [comment]
This LGTM. I've added a test to check if we experiment performance regressions future. /cc @jsvd

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java [hunk 1]
```diff
@@ -393,21 +394,18 @@ private static MethodLevelSyntaxElement callFilterFlush(final ClassFields fields
...
+        );
     }
 
-    private static MethodLevelSyntaxElement generateLog4jContextAssignment(IRubyObject pluginId) {
-        return () -> "org.apache.logging.log4j.ThreadContext.put(\"plugin.id\", \"" + pluginId + "\")";
+    private static MethodLevelSyntaxElement setPluginIdForLog4j(final ValueSyntaxElement plugin) {
+        return SyntaxFactory.value("org.apache.logging.log4j.ThreadContext").call(
+                "put",
+                SyntaxFactory.value("\"plugin.id\""),
+                plugin.call("getId").call("toString")
```
Comment (jsvd) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java:407]: maybe we should avoid the cost of converting a RubyString to String on every call by introducing a String rawID to the FilterDelegatorExt?

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java [hunk 2]
```diff
@@ -560,4 +564,130 @@ public Filter buildFilter(final String name, final String id,
...
+        });
+        System.out.println(String.format(">>>DNADBG compilation test took: %d seconds", compilationTest));
+
+        // sanity checks
+        final Collection<JrubyEventExtLibrary.RubyEvent> outputEvents = EVENT_SINKS.get(runId);
+        MatcherAssert.assertThat(outputEvents.size(), CoreMatchers.is(2));
+        MatcherAssert.assertThat(outputEvents.contains(testEvent), CoreMatchers.is(true));
+
+        // regression check
+        final String testMessage = "regression in pipeline compilation, twice the filters require more than twice " +
```
Comment (jsvd) [inline logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:603]: I think the tests here should not reflect on time taken to compile, but on the cache reuse.
The test should check that compiling two filters in the same position of the filter stage should be cached even if the ID is different.

Comment (jsvd) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:603]: and just to be clear, we need these tests included in this PR, but I think they should belong in a performance regression test suite.
however this PR addresses an issue where classes could no longer be reused from the cache and that's what the test should hit on.

Comment (andsel) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:603]: Sounds reasonable, I ask why the "should check that compiling two filters in the same position of the filter stage", the caching happens on the generated code, so the position inside the pipeline  shouldn't have effect?

Comment (jsvd) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:603]: the generated code still references the previous dataset, e.g dataset 620 references 619:

```
  public CompiledDataset620(java.util.Map arguments) {
    field0 = ((org.logstash.generated.CompiledDataset619) arguments.get("field0"));
    field1 = ((org.jruby.RubyArray) arguments.get("field1"));
    field2 = ((org.logstash.config.ir.compiler.OutputDelegatorExt) arguments.get("field2"));
  }
```

So even if `CompiledDataset602` is scrubbed from the code text, the 619 is still there.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java (hunk 1 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java:407]: The `id` is a `RubyString`

https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java#L49

This is certainly a very marginal optimization.

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java (hunk 2 above)
Comment (colinsurprenant) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:603]: agree, timing/performance related tests should be better done in integration tests.

Comment (andsel) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:627]: we can't scrub that because if we so then we loose callsite for the previous filter

**Comment by jsvd** [comment]
Test has failed:
```
17:10:22 org.logstash.config.ir.CompiledPipelineTest > testCompilerCacheCompiledClasses FAILED
17:10:22     java.lang.AssertionError: expected:<1> but was:<0>
17:10:22         at org.junit.Assert.fail(Assert.java:88)
17:10:22         at org.junit.Assert.failNotEquals(Assert.java:834)
17:10:22         at org.junit.Assert.assertEquals(Assert.java:645)
17:10:22         at org.junit.Assert.assertEquals(Assert.java:631)
17:10:22         at org.logstash.config.ir.CompiledPipelineTest.testCompilerCacheCompiledClasses(CompiledPipelineTest.java:590)
```

**Comment by andsel** [comment]
@jsvd I think the cache is already warmed up by other tests

**Comment by jsvd** [comment]
good catch, @andsel can you open an issue to discuss the implementation of the cache as a static? as it is it's difficult to configure/disable the cache in testing.
In the meantime we can simply evict the cache before tests in this class.

**Comment by andsel** [comment]
Added issue #12044 to improve the internal class cache

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java (hunk 2 above)
Comment (yaauie) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:627]: !!! @jsvd  -- I think your comment above about referencing previous datasets has knocked something loose in my brain. 

I'm pretty confident that we _don't_ need to reference previous datasets, which would make units significantly more cacheable and potentially eliminate the need for the global lock. Preliminary tests with the below generates code that _doesn't_ reference specific datasets, and seems to work, at least with moderate complexity if/else chaining.

~~~ diff
diff --git a/logstash-core/src/main/java/org/logstash/config/ir/compiler/VariableDefinition.java b/logstash-core/src/main/java/org/logstash/config/ir/compiler/VariableDefinition.java
index e6644cca6..83013003b 100644
--- a/logstash-core/src/main/java/org/logstash/config/ir/compiler/VariableDefinition.java
+++ b/logstash-core/src/main/java/org/logstash/config/ir/compiler/VariableDefinition.java
@@ -72,6 +72,8 @@ final class VariableDefinition implements SyntaxElement {
             safe = EventCondition.class;
         } else if (DynamicMethod.class.isAssignableFrom(clazz)) {
             safe = DynamicMethod.class;
+        } else if (BaseDataset.class.isAssignableFrom(clazz)) {
+            safe = BaseDataset.class;
         } else {
             safe = clazz;
         }
~~~

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java [hunk 3]
```diff
@@ -51,6 +52,10 @@
 
     private static final ISimpleCompiler COMPILER = new SimpleCompiler();
 
+    static {
+        COMPILER.setDebuggingInformation(true, true, true);
+    }
+
```
Comment (jsvd) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:58]: I don't believe this was intended to stay?

```suggestion
```

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java [hunk 4]
```diff
@@ -560,4 +563,156 @@ public Filter buildFilter(final String name, final String id,
...
+        public AbstractFilterDelegatorExt buildFilter(RubyString name, SourceWithMetadata source, IRubyObject args, Map<String, Object> pluginArgs) {
+//  for 7.7
+            final RubyObject configNameDouble = org.logstash.config.ir.PluginConfigNameMethodDouble.create(name);
+            return new FilterDelegatorExt(
+                    RubyUtil.RUBY, RubyUtil.FILTER_DELEGATOR_CLASS)
+                    .initForTesting(this.filter.get(), configNameDouble);
+// for 7.6
+//            return new FilterDelegatorExt(
+//                    RubyUtil.RUBY, RubyUtil.FILTER_DELEGATOR_CLASS)
+//                    .initForTesting(this.filter.get());
```
Comment (jsvd) [inline logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:705]: we won't be backporting this to 7.6

```suggestion
```

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java [hunk 5]
```diff
@@ -560,4 +563,156 @@ public Filter buildFilter(final String name, final String id,
...
+        compiledPipeline1.buildExecution();
+        final int cachedBefore = ComputeStepSyntaxElement.classCacheSize();
+
+        final PipelineIR pipeline2 = ConfigCompiler.configToPipelineIR(
+                IRHelpers.toSourceWithMetadataFromPath("org/logstash/config/ir/cache/pipeline2.conf"),
+                false);
+        final CompiledPipeline compiledPipeline2 = new CompiledPipeline(pipeline2, pluginFactory);
+        compiledPipeline2.buildExecution();
+        final int cachedAfter = ComputeStepSyntaxElement.classCacheSize();
+        System.out.println("DNADBG>> cachedAfter: " + cachedAfter + ", cachedBefore: " + cachedBefore);
```
Comment (jsvd) [inline logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:590]: what's  DNADBG?

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 3 above)
Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:58]: I was thinking the same, but if the switch for Janino debug is on, probably having the right line reference on the generated sources could be helpful.

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java (hunk 4 above)
Comment (andsel) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:705]: yes to remote, by bad

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java (hunk 5 above)
Comment (andsel) [reply logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:590]: ehm, comment to remove, my bad

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java (hunk 3 above)
Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:58]: Do you think could impact negatively the compilation part?

Comment (jsvd) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:58]: I haven't tested. can't this be enabled through JAVA_OPTS?

Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/ComputeStepSyntaxElement.java:58]: I found it, it's `org.codehaus.janino.source_debugging.enable` so removed the code fragment

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java [hunk 6]
```diff
@@ -47,16 +51,15 @@
 import org.logstash.RubyUtil;
 import org.logstash.common.IncompleteSourceWithMetadataException;
 import org.logstash.common.SourceWithMetadata;
-import org.logstash.config.ir.compiler.AbstractFilterDelegatorExt;
-import org.logstash.config.ir.compiler.AbstractOutputDelegatorExt;
-import org.logstash.config.ir.compiler.FilterDelegatorExt;
-import org.logstash.config.ir.compiler.PluginFactory;
+import org.logstash.config.ir.compiler.*;
```
Comment (jsvd) [inline logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:54]: let's avoid these refactors, I think we benefit from having an explicit list, makes it easier to understand the dependencies. Intellij can be [told to stop doing this](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports2).

File: logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java [hunk 7]
```diff
@@ -560,4 +563,150 @@ public Filter buildFilter(final String name, final String id,
...
+        final int cachedBefore = ComputeStepSyntaxElement.classCacheSize();
+
+        final PipelineIR pipeline2 = ConfigCompiler.configToPipelineIR(
+                IRHelpers.toSourceWithMetadataFromPath("org/logstash/config/ir/cache/pipeline2.conf"),
+                false);
+        final CompiledPipeline compiledPipeline2 = new CompiledPipeline(pipeline2, pluginFactory);
+        compiledPipeline2.buildExecution();
+        final int cachedAfter = ComputeStepSyntaxElement.classCacheSize();
+        final String message = String.format("unexpected cache size, cachedAfter: %d, cachedBefore: %d", cachedAfter, cachedBefore);
+        assertEquals(message, 1, cachedAfter - cachedBefore);
```
Comment (jsvd) [inline logstash-core/src/test/java/org/logstash/config/ir/CompiledPipelineTest.java:595]: Think back to rspec tests and how the framework gives us `let()` and other tools to remove preparation content from the test itself, I'd suggest grouping together the setup and then the test. Example:

```suggestion
        final FixedPluginFactory pluginFactory = new FixedPluginFactory(
                () -> null,
                () -> IDENTITY_FILTER,
                mockOutputSupplier()
        );

        final PipelineIR baselinePipeline = ConfigCompiler.configToPipelineIR(
                IRHelpers.toSourceWithMetadataFromPath("org/logstash/config/ir/cache/pipeline1.conf"),
                false);
        final CompiledPipeline cBaselinePipeline = new CompiledPipeline(baselinePipeline, pluginFactory);

        final PipelineIR pipelineWithExtraFilter = ConfigCompiler.configToPipelineIR(
                IRHelpers.toSourceWithMetadataFromPath("org/logstash/config/ir/cache/pipeline2.conf"),
                false);
        final CompiledPipeline cPipelineWithExtraFilter = new CompiledPipeline(pipelineWithExtraFilter, pluginFactory);
        
        // actual test: compiling a pipeline with an extra filter should only create 1 extra class
        ComputeStepSyntaxElement.cleanClassCache();
        cBaselinePipeline.buildExecution();
        final int cachedBefore = ComputeStepSyntaxElement.classCacheSize();
        cPipelineWithExtraFilter.buildExecution();
        final int cachedAfter = ComputeStepSyntaxElement.classCacheSize();
        
        final String message = String.format("unexpected cache size, cachedAfter: %d, cachedBefore: %d", cachedAfter, cachedBefore);
        assertEquals(message, 1, cachedAfter - cachedBefore);
```

**Comment by colinsurprenant** [comment]
Thanks @jsvd for the review and @andsel for moving this to completion with the added tests. 🚀
