### PR TITLE
Rebatch after filters when using pipeline.ordered

### LINKED ISSUE #11550: improve `pipeline.ordered` setting to rebatch before outputs
In #11524 we introduced the `pipeline.ordered` setting to solve the single-worker event ordering preservation that was broken under the Java execution. 

This fix is suboptimal in the sense that the implementation drips a batch event down the filter+output computation leading to having the outputs `multi_receive` work with events one-by-one instead of a complete batch. This will negatively impact performance for outputs such as the elasticsearch output which leverages a batch to perform a bulk operation. 

As discussed in https://github.com/elastic/logstash/pull/11524#issuecomment-578846896 one potential fix would be to try to re-aggregate a batch after the filtering but before the outputs.

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #11550
Relates to #11175

#### WIP TODOs
- [x] major cleanup
- [x] refactor & simplify the `filtersExecution` + `lastFilter` logic
- [x] re-enable and fix relevant java tests
- [x] benchmark

#### Description
When using `pipeline.ordered` the batch events are sent 1 by 1 down the filters and output. This PR rebatches after the filters so that full batches can be sent to the outputs. It does that by separating the filters and output execution with the introduction of a separator vertex in the pipeline graph between the filters and outputs and compiling both sections separately and in the worker_loop calling both compute separately which provides the possibility to rebatch after the filters.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
Unrelated build failure I restarted the failed build and it is now green https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-1/1161/

**Comment by colinsurprenant** [comment]
I performed the same benchmarks as in https://github.com/elastic/logstash/pull/11524#issuecomment-578220606 (but on different hardware, but it's not really important since relative numbers are interesting here).  Also, I noticed variations of ~5-10% between runs with the same parameters which I attribute to CPU throttling. 

## Config1
#### Java Execution

pipeline.ordered |  TPS master | TPS PR
------------- | ------------- | -------------:
false | 158k/s | 156k/s
true | 80k/s | **155k/s**

#### Ruby Execution

pipeline.ordered | TPS master | TPS PR
------------- | ------------- | -------------:
false/true  | 152k/s | 157k/s

## Config2
#### Java Execution

pipeline.ordered |  TPS master | TPS PR
------------- | ------------- | -------------:
false | 70k/s | 75k/s
true | 38k/s | **56k/s**

#### Ruby Execution

pipeline.ordered | TPS master | TPS PR
------------- | ------------- | -------------:
false/true  | 60k/s | 63k/s

File: logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+            return new SeparatorVertex(this.getId());
+        } catch (IncompleteSourceWithMetadataException e) {
+            // Never happens
+            throw new RuntimeException(e);
+        }
+    }
+
+    @Override
+    public boolean sourceComponentEquals(SourceComponent other) {
+        return other instanceof SeparatorVertex;
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java]: should `id` be factored in here? It looks like we always create with the same id, so either that should be factored in here or we should not have that as state. Being half-way between where we require it but also ignore it is an opportunity for future bugs.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 2]
```diff
@@ -312,30 +317,94 @@ private boolean isOutput(final Vertex vertex) {
...
+        public void compute(final RubyArray batch, final boolean flush, final boolean shutdown) {
+            unorderedCompute(batch, flush, shutdown);
         }
 
-        Dataset toDataset() {
-            return compiled;
+        @SuppressWarnings("rawtypes")
+        public void unorderedCompute(final RubyArray batch, final boolean flush, final boolean shutdown) {
+            @SuppressWarnings("unchecked") final RubyArray<JrubyEventExtLibrary.RubyEvent> outputBatch = RubyUtil.RUBY.newArray();
+            copyNonCancelledEvents(compiledFilters.compute(batch, flush, shutdown), outputBatch);
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: nitpick: I would rather see a local variable here with the result of the computation, which is then passed to `copyNonCancelledEvents`. There is a lot going on, and especially because some of these functions modify the passed collections in-place, it is easy to lose track of the objects.

File: logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java [hunk 3]
```diff
@@ -63,6 +66,9 @@ public PipelineIR(Graph inputSection, Graph filterSection, Graph outputSection,
         // Now we connect the queue to the root of the filter section
         tempGraph = tempGraph.chain(filterSection);
 
+        // Connect the filter section to the filter end vertex to separate from the output section
+        tempGraph = tempGraph.chain(new SeparatorVertex("filter_to_output"));
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java]: if we are hard-coding the id of all separator vertices to a single constant-value string, does it need to be a required parameter to the constructor method? ~And if `SeparatorVertex` is only ever instantiated with a constant `id` and carries no other state, can we reliably use a static singleton instead of instantiating a new one for each pipeline?~ (EDIT: superclass `Vertex` has much state)

File: logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java [hunk 4]
```diff
@@ -432,7 +432,7 @@ public boolean isEmpty() {
 
     public String uniqueHash() {
         return Util.digest(this.vertices().
-                filter(v -> !(v instanceof QueueVertex)). // has no metadata
+                filter(v -> !(v instanceof QueueVertex) && !(v instanceof SeparatorVertex)). // has no metadata
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java]: nitpick: perhaps `Vertex` should have a method like `Vertex#has_metadata` so we could filter on behaviour instead of a growing list of exceptions.

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java [hunk 5]
```diff
@@ -109,17 +111,12 @@ public void run() {
         }
     }
 
-    @SuppressWarnings("unchecked")
-    private void compute(final QueueBatch batch, final boolean flush, final boolean shutdown) {
+    @SuppressWarnings({"unchecked", "rawtypes"})
+    private void compute(final RubyArray batch, final boolean flush, final boolean shutdown) {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: We can probably keep this interface as a `QueueBatch`, and push the `to_a` down into the implementation of `execution#orderedCompute`, which will allow us to avoid the arrayification cost in unordered execution mode.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 6]
```diff
@@ -98,6 +102,8 @@
      */
     private final RubyIntegration.PluginFactory pluginFactory;
 
+    private CompiledExecution compiledExecution;
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: nitpick: never used

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 7]
```diff
@@ -312,30 +317,94 @@ private boolean isOutput(final Vertex vertex) {
...
+        /**
+         * Instantiates the graph of compiled filter section {@link Dataset}.
+         * @return Compiled {@link Dataset} representing the filter section of the pipeline.
+         */
+        private Dataset compileFilters() {
+            final Optional<Vertex> filterOutputSeparator = pipelineIR.getGraph()
+                .vertices()
+                .filter(v -> v instanceof SeparatorVertex)
+                .findFirst();
+            if (!filterOutputSeparator.isPresent()) {
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: nitpick: `filterOutputSeparator` is checked and then red. We could simplify with:
```java
final Collection<Vertex> filterNodes = filterOutputSeparator
   .orElseThrow(() -> new IllegalStateException("Missing Filter End Vertex"))
   .getIncomingVertices()....
```

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 8]
```diff
@@ -312,30 +317,94 @@ private boolean isOutput(final Vertex vertex) {
...
+                .collect(Collectors.toList());
+            if (filterNodes.isEmpty()) {
+                return Dataset.IDENTITY;
+            } else {
+                return DatasetCompiler.terminalFilterDataset(filterNodes.stream()
+                    .map(leaf -> {
+                        if (leaf instanceof PluginVertex) {
+                            return filterDataset(leaf, flatten(Collections.emptyList(), leaf));
+                        } else {
+                            // can only be a PluginVertex or an IfVertex
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: Can be only an `IfVertex` because the case of `PluginVertex` is checked by if

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 9]
```diff
@@ -312,30 +317,94 @@ private boolean isOutput(final Vertex vertex) {
...
+            // filter out the QueueVertex if there are no filters
+            final Collection<Vertex> filterNodes = filterOutputSeparator.get().getIncomingVertices()
+                .stream()
+                .filter(v -> v instanceof PluginVertex || v instanceof IfVertex)
+                .collect(Collectors.toList());
+            if (filterNodes.isEmpty()) {
+                return Dataset.IDENTITY;
+            } else {
+                return DatasetCompiler.terminalFilterDataset(filterNodes.stream()
+                    .map(leaf -> {
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: personal taste: the code inside map, being not trivial could be probably extracted in a private method with a name like `trasformFilterVertexToDataSet`

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java [hunk 10]
```diff
@@ -128,15 +134,58 @@ private DatasetCompiler() {
...
+                ),
+                parentFields,
+                inputBufferField
+            );
+            return prepare(withOutputBuffering(compute, clear, outputBuffer, fields)).instantiate();
+        } else if (count == 1) {
+            // No need for a terminal dataset here, if there is only a single parent node we can
+            // call it directly.
+            return parents.iterator().next();
+        } else {
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java]: personal taste: if this is like an "assert" I would probably put as first line, like:
```java
if (parents.isEmpty()) {
    throw new IllegalArgumentException(
           "Cannot create terminal filter dataset for an empty number of parent datasets"
    );
}
```

File: logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java [hunk 11]
```diff
@@ -0,0 +1,64 @@
...
+
+    // Special vertices really have no metadata
+    @Override
+    public SourceWithMetadata getSourceWithMetadata() {
+        return null;
+    }
+
+    @Override
+    public String uniqueHash() {
+        return Util.digest("SEPARATOR_" + this.getId());
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java]: I think this could generate recursion:
- this.getId() is Vertex.getId()
- Vertex.getId() check this.getSourceWithMetadata() (in this case is null)
- Vertex.getId() in case of null invokes this.uniqueHash()

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java [hunk 12]
```diff
@@ -109,17 +111,12 @@ public void run() {
...
         if (preserveEventOrder) {
-            // send batch events one-by-one as single-element batches
-            @SuppressWarnings({"rawtypes"}) final RubyArray singleElementBatch = RubyUtil.RUBY.newArray(1);
-            batch.to_a().forEach((e) -> {
-                singleElementBatch.set(0, e);
-                execution.compute(singleElementBatch, flush, shutdown);
-            });
+            execution.orderedCompute(batch, flush, shutdown);
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: Good idea, let me look at that.

File: logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java [hunk 13]
```diff
@@ -0,0 +1,64 @@
...
+
+    @Override
+    public boolean sourceComponentEquals(SourceComponent other) {
+        return other instanceof SeparatorVertex;
+    }
+
+    // Special vertices really have no metadata
+    @Override
+    public SourceWithMetadata getSourceWithMetadata() {
+        return null;
```
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java]: TBH I did not pay too much attention to the actual Vertex impl, I essentially copypasta the QueueVertex and renamed it to SeparatorVertex and modified it to be able to pass it an explicit ID at construction; my idea here was that separators could be used for other purposes eventually and my hidden agenda 😉 was to replace the QueueVertex with the SeparatorVertex (with a "QUEUE" ID) since this is what the QueueVertex is actually, just a separator too but this is out of scope for this PR. 

For now I do not think we need to specifically address this null return in this PR since that's essentially the same semantic as with the QueueVertex, maybe something to look at for in an followup PR where we could also look at just using the SeparatorVertex? WDYT?

File: logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java (hunk 1 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java]: Good catch.

File: logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java (hunk 3 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java]: As I commented above, my idea was that a SeparatorVertex could possibly used for multiple purposes, and even replace the QueueVertex, so the ID becomes the differentiator. I originally had a specific "FilterToOutputVertex" but figured these "separators" (that one and the QueueVertex) had the same purpose in the end so I opted to make it multi purpose. Maybe that's not the best approach and a more OO strategy with something like 
```java
abstract class SeparatorVertex extends Vertex {}

class FilterToOutputVertex extends SeparatorVertex{}

//and eventually
class QueueVertex extends SeparatorVertex {}
```
WDYT?

File: logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java (hunk 4 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/graph/Graph.java]: agree. I'll wait to see what you think of my other comments about the `Vertex` strategy.

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java (hunk 5 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: Good idea, let me look at that.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 6 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: Good catch. A leftover.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 7 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: Good idea. We can even go one step further with
```
            final Collection<Vertex> filterNodes = pipelineIR.getGraph()
                .vertices()
                .filter(v -> v instanceof SeparatorVertex)
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("Missing Filter End Vertex"))
                .getIncomingVertices()
                .stream()
                .filter(v -> v instanceof PluginVertex || v instanceof IfVertex)
                .collect(Collectors.toList());
```

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 8 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: I rephrased fro clarity.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java (hunk 10 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java]: Agree. will also do the same for both `terminalFilterDataset`  and `terminalOutputDataset`

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 9 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: yeah ... let me revisit this, I think we can simplify this further.

File: logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java (hunk 11 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/graph/SeparatorVertex.java]: Not for `SeparatorVertex` which always haas an `explicitId` set per the only constructor
```java
    public SeparatorVertex(String id) throws IncompleteSourceWithMetadataException {
        super(new SourceWithMetadata("internal", id, 0,0,"separator"), id);
    }
``` 
and `getId()` first checks for
```java
    public String getId() {
        if (explicitId != null) return explicitId;
```

**Comment by colinsurprenant** [comment]
Thanks a lot for the reviews @yaauie @andsel for the reviews!  I pushed some suggested modifications, will be working on others today. I'd also like your thoughts about the `SeparatorVertex` comments (keep as-is with an explicit ID or refactor into one more abstract class). LMKWYT.

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java (hunk 5 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: actually, ultimately the `compute` method take a `RubyArray` as parameter so conversion from a `QueueBatch` to a `RubyArray` must always happen. Because of that we can't really optimize the unordered case but the ordered could be optimized for the drip loop if we could expose a method that returns a `Collection` instead of using `to_a()` to iterate through all events.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 2 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: exposed result.

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java (hunk 5 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: I pushed changes for this.  We should definitely followup in another PR to simplify the `AckedReadBatch` impl, I added a comment to this effect.
LMKWYT.

File: logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java (hunk 3 above)
Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java]: If the 2 subclasses (`FilterToOutputVertex` and `QueueVertex`) are only placeholders and don't provide any behaviour probably is best to introduce an enum with the flavour of these vertices, this is more friendly in if/switch than `instanceof`, at least we are sure we don't put behaviour in those 2 subclasses

Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java]: good idea ... but `enum` can't extend `Vertex` so we would beed to refactor this even more, unless I am missing something simpler here?  If not I suggest we keep it like this and defer the `Vertex` / `SeparatorVertex` to another PR ? WDYT?

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: moved that logic up in CompiledPipeline.

File: logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java (hunk 3 above)
Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/PipelineIR.java]: I meant to add a `SeparatorType getType()` method to `SeparatorVertex` and define the `enum SeparatorType QUEUE, FILTER_TO_OUTPOUT`. But probably is best to make this happen in another PR, else we complicate this too much

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 9 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: ok, I fixed it, I overlooked the `flatten` method, much simpler now.

**Comment by colinsurprenant** [comment]
@andsel @yaauie I think we are ready for a another round of review - as per my comments 
- I suggest we leave the `SeparatorVertex` implementation as-is here and followup with a broader `Vertex` refactor which will include the `QueueVertex`.
- Also defer a `AckedReadBatch` refactor. There is some cleanups and simplifications to be done there but is out of scope here.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 9 above)
Comment (andsel) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: Much nicer now! I like it

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 14]
```diff
@@ -136,14 +140,26 @@ public CompiledPipeline(
...
-        return new CompiledPipeline.CompiledExecution().toDataset();
+    public CompiledPipeline.CompiledExecution buildExecution() {
+        return buildExecution(false);
     }
 
+    /**
+     * Perform the actual compilation of the {@link Dataset} representing the
+     * underlying pipeline from the Queue to the outputs using the ordered or
+     * unordered  execution model.
+     * @return CompiledPipeline.CompiledExecution the compiled pipeline
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: build fails without doc for the param

```suggestion
     * @param orderedExecution determines whether to build an execution that enforces order or not
     * @return CompiledPipeline.CompiledExecution the compiled pipeline
```

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 15]
```diff
@@ -294,12 +310,58 @@ private boolean isOutput(final Vertex vertex) {
...
+            });
+            compiledOutputs.compute(outputBatch, flush, shutdown);
+        }
+    }
+
+    public final class CompiledUnorderedExecution extends CompiledExecution {
+
+        @Override
+        public void compute(final QueueBatch batch, final boolean flush, final boolean shutdown) {
+            compute(batch.to_a(), flush, shutdown);
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: 🤔 so we end up needing this arrayification anyway, which appears to be a bit of a bummer.

File: logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java [hunk 16]
```diff
@@ -128,37 +134,82 @@ private DatasetCompiler() {
...
-            final Collection<ValueSyntaxElement> parentFields =
-                parents.stream().map(fields::add).collect(Collectors.toList());
-            result = compileOutput(
-                Closure.wrap(
-                    parentFields.stream().map(DatasetCompiler::computeDataset)
-                        .toArray(MethodLevelSyntaxElement[]::new)
-                ).add(clearSyntax(parentFields)), Closure.EMPTY, fields
-            ).instantiate();
-        } else if (count == 1) {
+        if (count == 1) {
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/config/ir/compiler/DatasetCompiler.java]: +1 to bringing the assertion and optimization cases up to the top.

File: logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java [hunk 17]
```diff
@@ -65,7 +60,7 @@ public WorkerLoop(
     {
         this.consumedCounter = consumedCounter;
         this.filteredCounter = filteredCounter;
-        this.execution = pipeline.buildExecution();
+        this.execution =  pipeline.buildExecution(preserveEventOrder);
```
Comment (yaauie) [inline logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java]: nitpick: extra space

```suggestion
        this.execution = pipeline.buildExecution(preserveEventOrder);
```

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java [hunk 18]
```diff
@@ -294,12 +310,58 @@ private boolean isOutput(final Vertex vertex) {
...
+        public void compute(final RubyArray batch, final boolean flush, final boolean shutdown) {
+            compute(batch, flush, shutdown);
+        }
+
+        @SuppressWarnings({"rawtypes", "unchecked"})
+        private void compute(final Collection batch, final boolean flush, final boolean shutdown) {
+            final RubyArray<RubyEvent> outputBatch = RubyUtil.RUBY.newArray();
+            // send batch one-by-one as single-element batches down the filters
+            final RubyArray<RubyEvent> filterBatch = RubyUtil.RUBY.newArray(1);
+            batch.forEach((e) -> {
```
Comment (andsel) [inline logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: Is it useful to have `forEach` invocation instead of plain for loop?

**Comment by andsel** [comment]
Only a really minor comment, LGTM

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 18 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: nope, will change.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 15 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: yeah, that't because the `compute` interface https://github.com/elastic/logstash/blob/aa931661c6773052e899b7c9fb7ee2d76ececcf2/logstash-core/src/main/java/org/logstash/config/ir/compiler/Dataset.java#L67 
takes a `RubyArray` as param. 
I will look into what could be done with that, these array conversions are very costly, I suggest we defer that into another issue though.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 14 above)
Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: ah, yes.

File: logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java (hunk 15 above)
Comment (yaauie) [reply logstash-core/src/main/java/org/logstash/config/ir/CompiledPipeline.java]: +1 to deferring

**Comment by colinsurprenant** [comment]
Thanks a lot @yaauie @andsel for the excellent reviews!

**Comment by colinsurprenant** [comment]
Merged in master (8.0), 7.x #11726 and 7.7 #11730
