### PR TITLE
DLQ-ing events that trigger an conditional evaluation error.

### LINKED ISSUE #16422: Send to DLQ events that trigger a fail on a condition evaluation
With #16322 was provided the handling of failures happening during conditional evaluation; with that the event is just logged.
Update the handling of failed evaluation to also send the offending event to DLQ if the executing pipeline has the setting `dead_letter_queue.enable` value to `true`

### PR DESCRIPTION
**Pull request by andsel**
## Release notes
When a conditional evaluation encounter an error in the expression the event that triggered the issue is sent to pipeline's DLQ, if enabled for the executing pipeline.

## What does this PR do?

This PR engage with the work done in #16322, the `ConditionalEvaluationListener` that is receives notifications about if-statements evaluation failure, is improved to also send the event to DLQ (if enabled in the pipeline) and not just logging it.

## Why is it important/What is the impact to the user?

Let the user that encounter errors in the evaluation of conditional statements to enqueue in DLQ for a subsequent processing.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

Use a pipeline that would trigger an error in conditional evaluation, like:
```
input {
    generator {
      message => '{"path":{"to":{"value": 101}}}'
      codec => json
      count => 1
    }
}

filter {
  if [path][to][value] > "100" { mutate { add_tag => "hit" } }
}

output {
    stdout { codec => rubydebug }
}
```
And enable DLQ, so in `config/logstash.yml` set
```
dead_letter_queue.enable: true
```

## Related issues

- Closes #16422 
- Relates #16322

### CODE REVIEW

File: logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java [hunk 1]
```diff
@@ -190,6 +191,15 @@ public void notify(ConditionalEvaluationError err) {
             } catch (IOException ioex) {
                 LOGGER.warn("Invalid operation on closing internal resources", ioex);
             }
+
+            // if pipeline has DLQ enabled, send also there the event
+            if (javaDlqWriter != null) {
```
Comment (jsvd) [inline logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java:196]: We should change the log entry to mention that the event was sent to the DLQ instead of "Event was dropped, enable debug logging to see the event's payload."

File: logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java [hunk 2]
```diff
@@ -190,6 +191,15 @@ public void notify(ConditionalEvaluationError err) {
...
+                try {
+                    javaDlqWriter.writeEntry(err.failedEvent(), "if-statement", "if-statement", "condition evaluation error, " + lastErrorEvaluationReceived);
```
Comment (jsvd) [inline logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java:198]: please open an issue to refactor the writeEntry to accept a "element_type" and "element_id" instead of "plugin_type" / "plugin_id", as it doesn't make sense with the addition of the conditionals, e.g.:

```json
{
          "path" => {
        "to" => {
            "value" => "101"
        }
    },
    "@timestamp" => 2024-09-17T14:45:27.888346Z,
     "@metadata" => {
        "dead_letter_queue" => {
             "entry_time" => 2024-09-17T14:45:27.999153Z,
              "plugin_id" => "if-statement",
            "plugin_type" => "if-statement",
                 "reason" => "condition evaluation error, Unexpected conditional input combination of '<no-class>:<null-value>' (left) and 'class org.jruby.RubyFixnum:100' (right)"
        }
    },
      "@version" => "1",
          "host" => {
        "name" => "arkham.local"
    },
       "message" => "{\"path\":{\"to\":{\"value\":\"101\"}}}"
}
```

Comment (andsel) [reply logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java:198]: Created #16463 to track this. Maybe the `element_type` for plugins remains the same as `plugin_type` and not `plugin_output`.
However since we are changing the format of the serialized data, could this be considered a breaking? Or at least we have to think about the fact that a future version of LS with the attributes renamed should be able to read a DLQ from a previous version. WDYT?

Comment (jsvd) [reply logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java:198]: we'll have to figure that out in that issue. we can either have a breaking change or add an extra field with the duplicate data and mark the others as deprecated.

File: logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java [hunk 3]
```diff
@@ -180,10 +181,32 @@ public final class LogErrorEvaluationListener implements ConditionalEvaluationLi
         @Override
         public void notify(ConditionalEvaluationError err) {
             lastErrorEvaluationReceived = err.getCause().getMessage();
-            LOGGER.warn("{}. Event was dropped, enable debug logging to see the event's payload.", lastErrorEvaluationReceived);
+            if (isDLQEnabled()) {
+                LOGGER.warn("{}. Failing event was sent to dead letter queue", lastErrorEvaluationReceived);
```
Comment (jsvd) [inline logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java:185]: Any reason for one to end on a period (`.`) and the other not?

Comment (andsel) [reply logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java:185]: No, was a typo

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by andsel** [comment]
@logstashmachine backport 8.x
