### PR TITLE
Windows freespace on SUBST'ed drives

### LINKED ISSUE #9123: Test failure: Master and 6.x failing for since January 24
https://logstash-ci.elastic.co/job/elastic-logstash-6.x/ and https://logstash-ci.elastic.co/job/elastic-logstash-master/

Some of the dependent jobs are succeeding, but at least one has failed every time for the past 15 days.

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #9123 

On Windows, SUBST'ed drives report `0L` as `getFreeSpace()`. 

API doc says:
```
The number of unallocated bytes on the partition or 0L if the abstract pathname does not name a partition [...]
```

There is no straightforward fix for this and it seems a fix is included in Java 9. 
One alternative is to launch and parse a DIR command and look at the reported free space.

This is a temporary fix to get the CI tests going which relies on SUBST'ed drives to manage long paths.

### CODE REVIEW

File: logstash-core/src/main/java/org/logstash/common/FsUtil.java [hunk 1]
```diff
@@ -36,6 +41,18 @@ public static boolean hasFreeSpace(final String path, final long size)
             }
         }
 
+        final long freeSpace = location.getFreeSpace();
+
+        if (freeSpace == 0L && IS_WINDOWS) {
```
Comment (danhermann) [inline logstash-core/src/main/java/org/logstash/common/FsUtil.java]: Is it worth adding a check here for Java versions <9 so that the free space test is re-enabled when run on Java versions with the fix for SUBST drives?

Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/common/FsUtil.java]: good idea - but first need to validate that it is indeed fixed in Java 9. Saw a JVM issue about it but did not go as far as testing it on Java 9.

Comment (colinsurprenant) [reply logstash-core/src/main/java/org/logstash/common/FsUtil.java]: @danhermann I just rana test on Java 9 and free space is still reported a `0L` on SUBST'ed drive so I think we should move forward, and I'll create a followup issue to see if we need to add and alternate free space strategy on Windows.

Comment (danhermann) [reply logstash-core/src/main/java/org/logstash/common/FsUtil.java]: Cool, sounds good to me

**Comment by danhermann** [comment]
LGTM

**Comment by colinsurprenant** [comment]
merged in master and 6.x
6.x commit is 5057e1be15f097026b4ad17ca6fabe02a58476c1
